/*
 * Copyright 2004-2010 Apple Computer, Inc., Mozilla Foundation, and Opera 
 * Software ASA.
 * 
 * You are granted a license to use, reproduce and create derivative works of 
 * this document.
 */

namespace HtmlParserSharp.Portable.Core
{
    public sealed class NamedCharacters
    {
        internal static readonly string[] NAMES =
            {
                "lig", "lig;",
                "P", "P;", "cute", "cute;", "reve;", "irc", "irc;", "y;", "r;",
                "rave", "rave;", "pha;", "acr;", "d;", "gon;", "pf;",
                "plyFunction;", "ing", "ing;", "cr;", "sign;", "ilde", "ilde;",
                "ml", "ml;", "ckslash;", "rv;", "rwed;", "y;", "cause;",
                "rnoullis;", "ta;", "r;", "pf;", "eve;", "cr;", "mpeq;", "cy;",
                "PY", "PY;", "cute;", "p;", "pitalDifferentialD;", "yleys;",
                "aron;", "edil", "edil;", "irc;", "onint;", "ot;", "dilla;",
                "nterDot;", "r;", "i;", "rcleDot;", "rcleMinus;", "rclePlus;",
                "rcleTimes;", "ockwiseContourIntegral;", "oseCurlyDoubleQuote;",
                "oseCurlyQuote;", "lon;", "lone;", "ngruent;", "nint;",
                "ntourIntegral;", "pf;", "product;",
                "unterClockwiseContourIntegral;", "oss;", "cr;", "p;", "pCap;",
                ";", "otrahd;", "cy;", "cy;", "cy;", "gger;", "rr;", "shv;",
                "aron;", "y;", "l;", "lta;", "r;", "acriticalAcute;",
                "acriticalDot;", "acriticalDoubleAcute;", "acriticalGrave;",
                "acriticalTilde;", "amond;", "fferentialD;", "pf;", "t;", "tDot;",
                "tEqual;", "ubleContourIntegral;", "ubleDot;", "ubleDownArrow;",
                "ubleLeftArrow;", "ubleLeftRightArrow;", "ubleLeftTee;",
                "ubleLongLeftArrow;", "ubleLongLeftRightArrow;",
                "ubleLongRightArrow;", "ubleRightArrow;", "ubleRightTee;",
                "ubleUpArrow;", "ubleUpDownArrow;", "ubleVerticalBar;", "wnArrow;",
                "wnArrowBar;", "wnArrowUpArrow;", "wnBreve;", "wnLeftRightVector;",
                "wnLeftTeeVector;", "wnLeftVector;", "wnLeftVectorBar;",
                "wnRightTeeVector;", "wnRightVector;", "wnRightVectorBar;",
                "wnTee;", "wnTeeArrow;", "wnarrow;", "cr;", "trok;", "G;", "H",
                "H;", "cute", "cute;", "aron;", "irc", "irc;", "y;", "ot;", "r;",
                "rave", "rave;", "ement;", "acr;", "ptySmallSquare;",
                "ptyVerySmallSquare;", "gon;", "pf;", "silon;", "ual;",
                "ualTilde;", "uilibrium;", "cr;", "im;", "a;", "ml", "ml;",
                "ists;", "ponentialE;", "y;", "r;", "lledSmallSquare;",
                "lledVerySmallSquare;", "pf;", "rAll;", "uriertrf;", "cr;", "cy;",
                "", ";", "mma;", "mmad;", "reve;", "edil;", "irc;", "y;", "ot;",
                "r;", ";", "pf;", "eaterEqual;", "eaterEqualLess;",
                "eaterFullEqual;", "eaterGreater;", "eaterLess;",
                "eaterSlantEqual;", "eaterTilde;", "cr;", ";", "RDcy;", "cek;",
                "t;", "irc;", "r;", "lbertSpace;", "pf;", "rizontalLine;", "cr;",
                "trok;", "mpDownHump;", "mpEqual;", "cy;", "lig;", "cy;", "cute",
                "cute;", "irc", "irc;", "y;", "ot;", "r;", "rave", "rave;", ";",
                "acr;", "aginaryI;", "plies;", "t;", "tegral;", "tersection;",
                "visibleComma;", "visibleTimes;", "gon;", "pf;", "ta;", "cr;",
                "ilde;", "kcy;", "ml", "ml;", "irc;", "y;", "r;", "pf;", "cr;",
                "ercy;", "kcy;", "cy;", "cy;", "ppa;", "edil;", "y;", "r;", "pf;",
                "cr;", "cy;", "", ";", "cute;", "mbda;", "ng;", "placetrf;", "rr;",
                "aron;", "edil;", "y;", "ftAngleBracket;", "ftArrow;",
                "ftArrowBar;", "ftArrowRightArrow;", "ftCeiling;",
                "ftDoubleBracket;", "ftDownTeeVector;", "ftDownVector;",
                "ftDownVectorBar;", "ftFloor;", "ftRightArrow;", "ftRightVector;",
                "ftTee;", "ftTeeArrow;", "ftTeeVector;", "ftTriangle;",
                "ftTriangleBar;", "ftTriangleEqual;", "ftUpDownVector;",
                "ftUpTeeVector;", "ftUpVector;", "ftUpVectorBar;", "ftVector;",
                "ftVectorBar;", "ftarrow;", "ftrightarrow;", "ssEqualGreater;",
                "ssFullEqual;", "ssGreater;", "ssLess;", "ssSlantEqual;",
                "ssTilde;", "r;", ";", "eftarrow;", "idot;", "ngLeftArrow;",
                "ngLeftRightArrow;", "ngRightArrow;", "ngleftarrow;",
                "ngleftrightarrow;", "ngrightarrow;", "pf;", "werLeftArrow;",
                "werRightArrow;", "cr;", "h;", "trok;", ";", "p;", "y;",
                "diumSpace;", "llintrf;", "r;", "nusPlus;", "pf;", "cr;", ";",
                "cy;", "cute;", "aron;", "edil;", "y;", "gativeMediumSpace;",
                "gativeThickSpace;", "gativeThinSpace;", "gativeVeryThinSpace;",
                "stedGreaterGreater;", "stedLessLess;", "wLine;", "r;", "Break;",
                "nBreakingSpace;", "pf;", "t;", "tCongruent;", "tCupCap;",
                "tDoubleVerticalBar;", "tElement;", "tEqual;", "tEqualTilde;",
                "tExists;", "tGreater;", "tGreaterEqual;", "tGreaterFullEqual;",
                "tGreaterGreater;", "tGreaterLess;", "tGreaterSlantEqual;",
                "tGreaterTilde;", "tHumpDownHump;", "tHumpEqual;",
                "tLeftTriangle;", "tLeftTriangleBar;", "tLeftTriangleEqual;",
                "tLess;", "tLessEqual;", "tLessGreater;", "tLessLess;",
                "tLessSlantEqual;", "tLessTilde;", "tNestedGreaterGreater;",
                "tNestedLessLess;", "tPrecedes;", "tPrecedesEqual;",
                "tPrecedesSlantEqual;", "tReverseElement;", "tRightTriangle;",
                "tRightTriangleBar;", "tRightTriangleEqual;", "tSquareSubset;",
                "tSquareSubsetEqual;", "tSquareSuperset;", "tSquareSupersetEqual;",
                "tSubset;", "tSubsetEqual;", "tSucceeds;", "tSucceedsEqual;",
                "tSucceedsSlantEqual;", "tSucceedsTilde;", "tSuperset;",
                "tSupersetEqual;", "tTilde;", "tTildeEqual;", "tTildeFullEqual;",
                "tTildeTilde;", "tVerticalBar;", "cr;", "ilde", "ilde;", ";",
                "lig;", "cute", "cute;", "irc", "irc;", "y;", "blac;", "r;",
                "rave", "rave;", "acr;", "ega;", "icron;", "pf;",
                "enCurlyDoubleQuote;", "enCurlyQuote;", ";", "cr;", "lash",
                "lash;", "ilde", "ilde;", "imes;", "ml", "ml;", "erBar;",
                "erBrace;", "erBracket;", "erParenthesis;", "rtialD;", "y;", "r;",
                "i;", ";", "usMinus;", "incareplane;", "pf;", ";", "ecedes;",
                "ecedesEqual;", "ecedesSlantEqual;", "ecedesTilde;", "ime;",
                "oduct;", "oportion;", "oportional;", "cr;", "i;", "OT", "OT;",
                "r;", "pf;", "cr;", "arr;", "G", "G;", "cute;", "ng;", "rr;",
                "rrtl;", "aron;", "edil;", "y;", ";", "verseElement;",
                "verseEquilibrium;", "verseUpEquilibrium;", "r;", "o;",
                "ghtAngleBracket;", "ghtArrow;", "ghtArrowBar;",
                "ghtArrowLeftArrow;", "ghtCeiling;", "ghtDoubleBracket;",
                "ghtDownTeeVector;", "ghtDownVector;", "ghtDownVectorBar;",
                "ghtFloor;", "ghtTee;", "ghtTeeArrow;", "ghtTeeVector;",
                "ghtTriangle;", "ghtTriangleBar;", "ghtTriangleEqual;",
                "ghtUpDownVector;", "ghtUpTeeVector;", "ghtUpVector;",
                "ghtUpVectorBar;", "ghtVector;", "ghtVectorBar;", "ghtarrow;",
                "pf;", "undImplies;", "ightarrow;", "cr;", "h;", "leDelayed;",
                "CHcy;", "cy;", "FTcy;", "cute;", ";", "aron;", "edil;", "irc;",
                "y;", "r;", "ortDownArrow;", "ortLeftArrow;", "ortRightArrow;",
                "ortUpArrow;", "gma;", "allCircle;", "pf;", "rt;", "uare;",
                "uareIntersection;", "uareSubset;", "uareSubsetEqual;",
                "uareSuperset;", "uareSupersetEqual;", "uareUnion;", "cr;", "ar;",
                "b;", "bset;", "bsetEqual;", "cceeds;", "cceedsEqual;",
                "cceedsSlantEqual;", "cceedsTilde;", "chThat;", "m;", "p;",
                "perset;", "persetEqual;", "pset;", "ORN", "ORN;", "ADE;", "Hcy;",
                "cy;", "b;", "u;", "aron;", "edil;", "y;", "r;", "erefore;",
                "eta;", "ickSpace;", "inSpace;", "lde;", "ldeEqual;",
                "ldeFullEqual;", "ldeTilde;", "pf;", "ipleDot;", "cr;", "trok;",
                "cute", "cute;", "rr;", "rrocir;", "rcy;", "reve;", "irc", "irc;",
                "y;", "blac;", "r;", "rave", "rave;", "acr;", "derBar;",
                "derBrace;", "derBracket;", "derParenthesis;", "ion;", "ionPlus;",
                "gon;", "pf;", "Arrow;", "ArrowBar;", "ArrowDownArrow;",
                "DownArrow;", "Equilibrium;", "Tee;", "TeeArrow;", "arrow;",
                "downarrow;", "perLeftArrow;", "perRightArrow;", "si;", "silon;",
                "ing;", "cr;", "ilde;", "ml", "ml;", "ash;", "ar;", "y;", "ash;",
                "ashl;", "e;", "rbar;", "rt;", "rticalBar;", "rticalLine;",
                "rticalSeparator;", "rticalTilde;", "ryThinSpace;", "r;", "pf;",
                "cr;", "dash;", "irc;", "dge;", "r;", "pf;", "cr;", "r;", ";",
                "pf;", "cr;", "cy;", "cy;", "cy;", "cute", "cute;", "irc;", "y;",
                "r;", "pf;", "cr;", "ml;", "cy;", "cute;", "aron;", "y;", "ot;",
                "roWidthSpace;", "ta;", "r;", "pf;", "cr;", "cute", "cute;",
                "reve;", ";", "E;", "d;", "irc", "irc;", "ute", "ute;", "y;",
                "lig", "lig;", ";", "r;", "rave", "rave;", "efsym;", "eph;",
                "pha;", "acr;", "alg;", "p", "p;", "d;", "dand;", "dd;", "dslope;",
                "dv;", "g;", "ge;", "gle;", "gmsd;", "gmsdaa;", "gmsdab;",
                "gmsdac;", "gmsdad;", "gmsdae;", "gmsdaf;", "gmsdag;", "gmsdah;",
                "grt;", "grtvb;", "grtvbd;", "gsph;", "gst;", "gzarr;", "gon;",
                "pf;", ";", "E;", "acir;", "e;", "id;", "os;", "prox;", "proxeq;",
                "ing", "ing;", "cr;", "t;", "ymp;", "ympeq;", "ilde", "ilde;",
                "ml", "ml;", "conint;", "int;", "ot;", "ckcong;", "ckepsilon;",
                "ckprime;", "cksim;", "cksimeq;", "rvee;", "rwed;", "rwedge;",
                "rk;", "rktbrk;", "ong;", "y;", "quo;", "caus;", "cause;",
                "mptyv;", "psi;", "rnou;", "ta;", "th;", "tween;", "r;", "gcap;",
                "gcirc;", "gcup;", "godot;", "goplus;", "gotimes;", "gsqcup;",
                "gstar;", "gtriangledown;", "gtriangleup;", "guplus;", "gvee;",
                "gwedge;", "arow;", "acklozenge;", "acksquare;", "acktriangle;",
                "acktriangledown;", "acktriangleleft;", "acktriangleright;",
                "ank;", "k12;", "k14;", "k34;", "ock;", "e;", "equiv;", "ot;",
                "pf;", "t;", "ttom;", "wtie;", "xDL;", "xDR;", "xDl;", "xDr;",
                "xH;", "xHD;", "xHU;", "xHd;", "xHu;", "xUL;", "xUR;", "xUl;",
                "xUr;", "xV;", "xVH;", "xVL;", "xVR;", "xVh;", "xVl;", "xVr;",
                "xbox;", "xdL;", "xdR;", "xdl;", "xdr;", "xh;", "xhD;", "xhU;",
                "xhd;", "xhu;", "xminus;", "xplus;", "xtimes;", "xuL;", "xuR;",
                "xul;", "xur;", "xv;", "xvH;", "xvL;", "xvR;", "xvh;", "xvl;",
                "xvr;", "rime;", "eve;", "vbar", "vbar;", "cr;", "emi;", "im;",
                "ime;", "ol;", "olb;", "olhsub;", "ll;", "llet;", "mp;", "mpE;",
                "mpe;", "mpeq;", "cute;", "p;", "pand;", "pbrcup;", "pcap;",
                "pcup;", "pdot;", "ps;", "ret;", "ron;", "aps;", "aron;", "edil",
                "edil;", "irc;", "ups;", "upssm;", "ot;", "dil", "dil;", "mptyv;",
                "nt", "nt;", "nterdot;", "r;", "cy;", "eck;", "eckmark;", "i;",
                "r;", "rE;", "rc;", "rceq;", "rclearrowleft;", "rclearrowright;",
                "rcledR;", "rcledS;", "rcledast;", "rcledcirc;", "rcleddash;",
                "re;", "rfnint;", "rmid;", "rscir;", "ubs;", "ubsuit;", "lon;",
                "lone;", "loneq;", "mma;", "mmat;", "mp;", "mpfn;", "mplement;",
                "mplexes;", "ng;", "ngdot;", "nint;", "pf;", "prod;", "py", "py;",
                "pysr;", "arr;", "oss;", "cr;", "ub;", "ube;", "up;", "upe;",
                "dot;", "darrl;", "darrr;", "epr;", "esc;", "larr;", "larrp;",
                "p;", "pbrcap;", "pcap;", "pcup;", "pdot;", "por;", "ps;", "rarr;",
                "rarrm;", "rlyeqprec;", "rlyeqsucc;", "rlyvee;", "rlywedge;",
                "rren", "rren;", "rvearrowleft;", "rvearrowright;", "vee;", "wed;",
                "conint;", "int;", "lcty;", "rr;", "ar;", "gger;", "leth;", "rr;",
                "sh;", "shv;", "karow;", "lac;", "aron;", "y;", ";", "agger;",
                "arr;", "otseq;", "g", "g;", "lta;", "mptyv;", "isht;", "r;",
                "arl;", "arr;", "am;", "amond;", "amondsuit;", "ams;", "e;",
                "gamma;", "sin;", "v;", "vide", "vide;", "videontimes;", "vonx;",
                "cy;", "corn;", "crop;", "llar;", "pf;", "t;", "teq;", "teqdot;",
                "tminus;", "tplus;", "tsquare;", "ublebarwedge;", "wnarrow;",
                "wndownarrows;", "wnharpoonleft;", "wnharpoonright;", "bkarow;",
                "corn;", "crop;", "cr;", "cy;", "ol;", "trok;", "dot;", "ri;",
                "rif;", "arr;", "har;", "angle;", "cy;", "igrarr;", "Dot;", "ot;",
                "cute", "cute;", "ster;", "aron;", "ir;", "irc", "irc;", "olon;",
                "y;", "ot;", ";", "Dot;", "r;", ";", "rave", "rave;", "s;",
                "sdot;", ";", "inters;", "l;", "s;", "sdot;", "acr;", "pty;",
                "ptyset;", "ptyv;", "sp13;", "sp14;", "sp;", "g;", "sp;", "gon;",
                "pf;", "ar;", "arsl;", "lus;", "si;", "silon;", "siv;", "circ;",
                "colon;", "sim;", "slantgtr;", "slantless;", "uals;", "uest;",
                "uiv;", "uivDD;", "vparsl;", "Dot;", "arr;", "cr;", "dot;", "im;",
                "a;", "h", "h;", "ml", "ml;", "ro;", "cl;", "ist;", "pectation;",
                "ponentiale;", "llingdotseq;", "y;", "male;", "ilig;", "lig;",
                "llig;", "r;", "lig;", "lig;", "at;", "lig;", "tns;", "of;", "pf;",
                "rall;", "rk;", "rkv;", "artint;", "ac12", "ac12;", "ac13;",
                "ac14", "ac14;", "ac15;", "ac16;", "ac18;", "ac23;", "ac25;",
                "ac34", "ac34;", "ac35;", "ac38;", "ac45;", "ac56;", "ac58;",
                "ac78;", "asl;", "own;", "cr;", ";", "l;", "cute;", "mma;",
                "mmad;", "p;", "reve;", "irc;", "y;", "ot;", ";", "l;", "q;",
                "qq;", "qslant;", "s;", "scc;", "sdot;", "sdoto;", "sdotol;",
                "sl;", "sles;", "r;", ";", "g;", "mel;", "cy;", ";", "E;", "a;",
                "j;", "E;", "ap;", "approx;", "e;", "eq;", "eqq;", "sim;", "pf;",
                "ave;", "cr;", "im;", "ime;", "iml;", "", ";", "cc;", "cir;",
                "dot;", "lPar;", "quest;", "rapprox;", "rarr;", "rdot;",
                "reqless;", "reqqless;", "rless;", "rsim;", "ertneqq;", "nE;",
                "rr;", "irsp;", "lf;", "milt;", "rdcy;", "rr;", "rrcir;", "rrw;",
                "ar;", "irc;", "arts;", "artsuit;", "llip;", "rcon;", "r;",
                "searow;", "swarow;", "arr;", "mtht;", "okleftarrow;",
                "okrightarrow;", "pf;", "rbar;", "cr;", "lash;", "trok;", "bull;",
                "phen;", "cute", "cute;", ";", "irc", "irc;", "y;", "cy;", "xcl",
                "xcl;", "f;", "r;", "rave", "rave;", ";", "iint;", "int;", "nfin;",
                "ota;", "lig;", "acr;", "age;", "agline;", "agpart;", "ath;",
                "of;", "ped;", ";", "care;", "fin;", "fintie;", "odot;", "t;",
                "tcal;", "tegers;", "tercal;", "tlarhk;", "tprod;", "cy;", "gon;",
                "pf;", "ta;", "rod;", "uest", "uest;", "cr;", "in;", "inE;",
                "indot;", "ins;", "insv;", "inv;", ";", "ilde;", "kcy;", "ml",
                "ml;", "irc;", "y;", "r;", "ath;", "pf;", "cr;", "ercy;", "kcy;",
                "ppa;", "ppav;", "edil;", "y;", "r;", "reen;", "cy;", "cy;", "pf;",
                "cr;", "arr;", "rr;", "tail;", "arr;", ";", "g;", "ar;", "cute;",
                "emptyv;", "gran;", "mbda;", "ng;", "ngd;", "ngle;", "p;", "quo",
                "quo;", "rr;", "rrb;", "rrbfs;", "rrfs;", "rrhk;", "rrlp;",
                "rrpl;", "rrsim;", "rrtl;", "t;", "tail;", "te;", "tes;", "arr;",
                "brk;", "race;", "rack;", "rke;", "rksld;", "rkslu;", "aron;",
                "edil;", "eil;", "ub;", "y;", "ca;", "quo;", "quor;", "rdhar;",
                "rushar;", "sh;", ";", "ftarrow;", "ftarrowtail;",
                "ftharpoondown;", "ftharpoonup;", "ftleftarrows;", "ftrightarrow;",
                "ftrightarrows;", "ftrightharpoons;", "ftrightsquigarrow;",
                "ftthreetimes;", "g;", "q;", "qq;", "qslant;", "s;", "scc;",
                "sdot;", "sdoto;", "sdotor;", "sg;", "sges;", "ssapprox;",
                "ssdot;", "sseqgtr;", "sseqqgtr;", "ssgtr;", "sssim;", "isht;",
                "loor;", "r;", ";", "E;", "ard;", "aru;", "arul;", "blk;", "cy;",
                ";", "arr;", "corner;", "hard;", "tri;", "idot;", "oust;",
                "oustache;", "E;", "ap;", "approx;", "e;", "eq;", "eqq;", "sim;",
                "ang;", "arr;", "brk;", "ngleftarrow;", "ngleftrightarrow;",
                "ngmapsto;", "ngrightarrow;", "oparrowleft;", "oparrowright;",
                "par;", "pf;", "plus;", "times;", "wast;", "wbar;", "z;", "zenge;",
                "zf;", "ar;", "arlt;", "arr;", "corner;", "har;", "hard;", "m;",
                "tri;", "aquo;", "cr;", "h;", "im;", "ime;", "img;", "qb;", "quo;",
                "quor;", "trok;", "", ";", "cc;", "cir;", "dot;", "hree;", "imes;",
                "larr;", "quest;", "rPar;", "ri;", "rie;", "rif;", "rdshar;",
                "ruhar;", "ertneqq;", "nE;", "Dot;", "cr", "cr;", "le;", "lt;",
                "ltese;", "p;", "psto;", "pstodown;", "pstoleft;", "pstoup;",
                "rker;", "omma;", "y;", "ash;", "asuredangle;", "r;", "o;", "cro",
                "cro;", "d;", "dast;", "dcir;", "ddot", "ddot;", "nus;", "nusb;",
                "nusd;", "nusdu;", "cp;", "dr;", "plus;", "dels;", "pf;", ";",
                "cr;", "tpos;", ";", "ltimap;", "map;", "g;", "t;", "tv;",
                "eftarrow;", "eftrightarrow;", "l;", "t;", "tv;", "ightarrow;",
                "Dash;", "dash;", "bla;", "cute;", "ng;", "p;", "pE;", "pid;",
                "pos;", "pprox;", "tur;", "tural;", "turals;", "sp", "sp;", "ump;",
                "umpe;", "ap;", "aron;", "edil;", "ong;", "ongdot;", "up;", "y;",
                "ash;", ";", "Arr;", "arhk;", "arr;", "arrow;", "dot;", "quiv;",
                "sear;", "sim;", "xist;", "xists;", "r;", "E;", "e;", "eq;",
                "eqq;", "eqslant;", "es;", "sim;", "t;", "tr;", "Arr;", "arr;",
                "par;", ";", "s;", "sd;", "v;", "cy;", "Arr;", "E;", "arr;", "dr;",
                "e;", "eftarrow;", "eftrightarrow;", "eq;", "eqq;", "eqslant;",
                "es;", "ess;", "sim;", "t;", "tri;", "trie;", "id;", "pf;", "t",
                "t;", "tin;", "tinE;", "tindot;", "tinva;", "tinvb;", "tinvc;",
                "tni;", "tniva;", "tnivb;", "tnivc;", "ar;", "arallel;", "arsl;",
                "art;", "olint;", "r;", "rcue;", "re;", "rec;", "receq;", "Arr;",
                "arr;", "arrc;", "arrw;", "ightarrow;", "tri;", "trie;", "c;",
                "ccue;", "ce;", "cr;", "hortmid;", "hortparallel;", "im;", "ime;",
                "imeq;", "mid;", "par;", "qsube;", "qsupe;", "ub;", "ubE;", "ube;",
                "ubset;", "ubseteq;", "ubseteqq;", "ucc;", "ucceq;", "up;", "upE;",
                "upe;", "upset;", "upseteq;", "upseteqq;", "gl;", "ilde", "ilde;",
                "lg;", "riangleleft;", "rianglelefteq;", "riangleright;",
                "rianglerighteq;", ";", "m;", "mero;", "msp;", "Dash;", "Harr;",
                "ap;", "dash;", "ge;", "gt;", "infin;", "lArr;", "le;", "lt;",
                "ltrie;", "rArr;", "rtrie;", "sim;", "Arr;", "arhk;", "arr;",
                "arrow;", "near;", ";", "cute", "cute;", "st;", "ir;", "irc",
                "irc;", "y;", "ash;", "blac;", "iv;", "ot;", "sold;", "lig;",
                "cir;", "r;", "on;", "rave", "rave;", "t;", "bar;", "m;", "nt;",
                "arr;", "cir;", "cross;", "ine;", "t;", "acr;", "ega;", "icron;",
                "id;", "inus;", "pf;", "ar;", "erp;", "lus;", ";", "arr;", "d;",
                "der;", "derof;", "df", "df;", "dm", "dm;", "igof;", "or;",
                "slope;", "v;", "cr;", "lash", "lash;", "ol;", "ilde", "ilde;",
                "imes;", "imesas;", "ml", "ml;", "bar;", "r;", "ra", "ra;",
                "rallel;", "rsim;", "rsl;", "rt;", "y;", "rcnt;", "riod;", "rmil;",
                "rp;", "rtenk;", "r;", "i;", "iv;", "mmat;", "one;", ";",
                "tchfork;", "v;", "anck;", "anckh;", "ankv;", "us;", "usacir;",
                "usb;", "uscir;", "usdo;", "usdu;", "use;", "usmn", "usmn;",
                "ussim;", "ustwo;", ";", "intint;", "pf;", "und", "und;", ";",
                "E;", "ap;", "cue;", "e;", "ec;", "ecapprox;", "eccurlyeq;",
                "eceq;", "ecnapprox;", "ecneqq;", "ecnsim;", "ecsim;", "ime;",
                "imes;", "nE;", "nap;", "nsim;", "od;", "ofalar;", "ofline;",
                "ofsurf;", "op;", "opto;", "sim;", "urel;", "cr;", "i;", "ncsp;",
                "r;", "nt;", "pf;", "rime;", "cr;", "aternions;", "atint;", "est;",
                "esteq;", "ot", "ot;", "arr;", "rr;", "tail;", "arr;", "ar;",
                "ce;", "cute;", "dic;", "emptyv;", "ng;", "ngd;", "nge;", "ngle;",
                "quo", "quo;", "rr;", "rrap;", "rrb;", "rrbfs;", "rrc;", "rrfs;",
                "rrhk;", "rrlp;", "rrpl;", "rrsim;", "rrtl;", "rrw;", "tail;",
                "tio;", "tionals;", "arr;", "brk;", "race;", "rack;", "rke;",
                "rksld;", "rkslu;", "aron;", "edil;", "eil;", "ub;", "y;", "ca;",
                "ldhar;", "quo;", "quor;", "sh;", "al;", "aline;", "alpart;",
                "als;", "ct;", "g", "g;", "isht;", "loor;", "r;", "ard;", "aru;",
                "arul;", "o;", "ov;", "ghtarrow;", "ghtarrowtail;",
                "ghtharpoondown;", "ghtharpoonup;", "ghtleftarrows;",
                "ghtleftharpoons;", "ghtrightarrows;", "ghtsquigarrow;",
                "ghtthreetimes;", "ng;", "singdotseq;", "arr;", "har;", "m;",
                "oust;", "oustache;", "mid;", "ang;", "arr;", "brk;", "par;",
                "pf;", "plus;", "times;", "ar;", "argt;", "polint;", "arr;",
                "aquo;", "cr;", "h;", "qb;", "quo;", "quor;", "hree;", "imes;",
                "ri;", "rie;", "rif;", "riltri;", "luhar;", ";", "cute;", "quo;",
                ";", "E;", "ap;", "aron;", "cue;", "e;", "edil;", "irc;", "nE;",
                "nap;", "nsim;", "polint;", "sim;", "y;", "ot;", "otb;", "ote;",
                "Arr;", "arhk;", "arr;", "arrow;", "ct", "ct;", "mi;", "swar;",
                "tminus;", "tmn;", "xt;", "r;", "rown;", "arp;", "chcy;", "cy;",
                "ortmid;", "ortparallel;", "y", "y;", "gma;", "gmaf;", "gmav;",
                "m;", "mdot;", "me;", "meq;", "mg;", "mgE;", "ml;", "mlE;", "mne;",
                "mplus;", "mrarr;", "arr;", "allsetminus;", "ashp;", "eparsl;",
                "id;", "ile;", "t;", "te;", "tes;", "ftcy;", "l;", "lb;", "lbar;",
                "pf;", "ades;", "adesuit;", "ar;", "cap;", "caps;", "cup;",
                "cups;", "sub;", "sube;", "subset;", "subseteq;", "sup;", "supe;",
                "supset;", "supseteq;", "u;", "uare;", "uarf;", "uf;", "arr;",
                "cr;", "etmn;", "mile;", "tarf;", "ar;", "arf;", "raightepsilon;",
                "raightphi;", "rns;", "b;", "bE;", "bdot;", "be;", "bedot;",
                "bmult;", "bnE;", "bne;", "bplus;", "brarr;", "bset;", "bseteq;",
                "bseteqq;", "bsetneq;", "bsetneqq;", "bsim;", "bsub;", "bsup;",
                "cc;", "ccapprox;", "cccurlyeq;", "cceq;", "ccnapprox;", "ccneqq;",
                "ccnsim;", "ccsim;", "m;", "ng;", "p1", "p1;", "p2", "p2;", "p3",
                "p3;", "p;", "pE;", "pdot;", "pdsub;", "pe;", "pedot;", "phsol;",
                "phsub;", "plarr;", "pmult;", "pnE;", "pne;", "pplus;", "pset;",
                "pseteq;", "pseteqq;", "psetneq;", "psetneqq;", "psim;", "psub;",
                "psup;", "Arr;", "arhk;", "arr;", "arrow;", "nwar;", "lig", "lig;",
                "rget;", "u;", "rk;", "aron;", "edil;", "y;", "ot;", "lrec;", "r;",
                "ere4;", "erefore;", "eta;", "etasym;", "etav;", "ickapprox;",
                "icksim;", "insp;", "kap;", "ksim;", "orn", "orn;", "lde;", "mes",
                "mes;", "mesb;", "mesbar;", "mesd;", "nt;", "ea;", "p;", "pbot;",
                "pcir;", "pf;", "pfork;", "sa;", "rime;", "ade;", "iangle;",
                "iangledown;", "iangleleft;", "ianglelefteq;", "iangleq;",
                "iangleright;", "ianglerighteq;", "idot;", "ie;", "iminus;",
                "iplus;", "isb;", "itime;", "pezium;", "cr;", "cy;", "hcy;",
                "trok;", "ixt;", "oheadleftarrow;", "oheadrightarrow;", "rr;",
                "ar;", "cute", "cute;", "rr;", "rcy;", "reve;", "irc", "irc;",
                "y;", "arr;", "blac;", "har;", "isht;", "r;", "rave", "rave;",
                "arl;", "arr;", "blk;", "corn;", "corner;", "crop;", "tri;",
                "acr;", "l", "l;", "gon;", "pf;", "arrow;", "downarrow;",
                "harpoonleft;", "harpoonright;", "lus;", "si;", "sih;", "silon;",
                "uparrows;", "corn;", "corner;", "crop;", "ing;", "tri;", "cr;",
                "dot;", "ilde;", "ri;", "rif;", "arr;", "ml", "ml;", "angle;",
                "rr;", "ar;", "arv;", "ash;", "ngrt;", "repsilon;", "rkappa;",
                "rnothing;", "rphi;", "rpi;", "rpropto;", "rr;", "rrho;",
                "rsigma;", "rsubsetneq;", "rsubsetneqq;", "rsupsetneq;",
                "rsupsetneqq;", "rtheta;", "rtriangleleft;", "rtriangleright;",
                "y;", "ash;", "e;", "ebar;", "eeq;", "llip;", "rbar;", "rt;", "r;",
                "tri;", "sub;", "sup;", "pf;", "rop;", "tri;", "cr;", "ubnE;",
                "ubne;", "upnE;", "upne;", "igzag;", "irc;", "dbar;", "dge;",
                "dgeq;", "ierp;", "r;", "pf;", ";", ";", "eath;", "cr;", "ap;",
                "irc;", "up;", "tri;", "r;", "Arr;", "arr;", ";", "Arr;", "arr;",
                "ap;", "is;", "dot;", "pf;", "plus;", "time;", "Arr;", "arr;",
                "cr;", "qcup;", "plus;", "tri;", "ee;", "edge;", "cute", "cute;",
                "cy;", "irc;", "y;", "n", "n;", "r;", "cy;", "pf;", "cr;", "cy;",
                "ml", "ml;", "cute;", "aron;", "y;", "ot;", "etrf;", "ta;", "r;",
                "cy;", "grarr;", "pf;", "cr;", "j;", "nj;"
            };

        internal static readonly char[][] VALUES = new[]
            {
                new[] {'\u00c6'}, new[] {'\u00c6'},
                new[] {'\u0026'}, new[] {'\u0026'}, new[] {'\u00c1'}, new[] {'\u00c1'},
                new[] {'\u0102'}, new[] {'\u00c2'}, new[] {'\u00c2'}, new[] {'\u0410'},
                new[] {'\ud835', '\udd04'}, new[] {'\u00c0'}, new[] {'\u00c0'}, new[] {'\u0391'},
                new[] {'\u0100'}, new[] {'\u2a53'}, new[] {'\u0104'}, new[] {'\ud835', '\udd38'},
                new[] {'\u2061'}, new[] {'\u00c5'}, new[] {'\u00c5'}, new[] {'\ud835', '\udc9c'},
                new[] {'\u2254'}, new[] {'\u00c3'}, new[] {'\u00c3'}, new[] {'\u00c4'},
                new[] {'\u00c4'}, new[] {'\u2216'}, new[] {'\u2ae7'}, new[] {'\u2306'},
                new[] {'\u0411'}, new[] {'\u2235'}, new[] {'\u212c'}, new[] {'\u0392'},
                new[] {'\ud835', '\udd05'}, new[] {'\ud835', '\udd39'}, new[] {'\u02d8'},
                new[] {'\u212c'}, new[] {'\u224e'}, new[] {'\u0427'}, new[] {'\u00a9'},
                new[] {'\u00a9'}, new[] {'\u0106'}, new[] {'\u22d2'}, new[] {'\u2145'},
                new[] {'\u212d'}, new[] {'\u010c'}, new[] {'\u00c7'}, new[] {'\u00c7'},
                new[] {'\u0108'}, new[] {'\u2230'}, new[] {'\u010a'}, new[] {'\u00b8'},
                new[] {'\u00b7'}, new[] {'\u212d'}, new[] {'\u03a7'}, new[] {'\u2299'},
                new[] {'\u2296'}, new[] {'\u2295'}, new[] {'\u2297'}, new[] {'\u2232'},
                new[] {'\u201d'}, new[] {'\u2019'}, new[] {'\u2237'}, new[] {'\u2a74'},
                new[] {'\u2261'}, new[] {'\u222f'}, new[] {'\u222e'}, new[] {'\u2102'},
                new[] {'\u2210'}, new[] {'\u2233'}, new[] {'\u2a2f'}, new[] {'\ud835', '\udc9e'},
                new[] {'\u22d3'}, new[] {'\u224d'}, new[] {'\u2145'}, new[] {'\u2911'},
                new[] {'\u0402'}, new[] {'\u0405'}, new[] {'\u040f'}, new[] {'\u2021'},
                new[] {'\u21a1'}, new[] {'\u2ae4'}, new[] {'\u010e'}, new[] {'\u0414'},
                new[] {'\u2207'}, new[] {'\u0394'}, new[] {'\ud835', '\udd07'}, new[] {'\u00b4'},
                new[] {'\u02d9'}, new[] {'\u02dd'}, new[] {'\u0060'}, new[] {'\u02dc'},
                new[] {'\u22c4'}, new[] {'\u2146'}, new[] {'\ud835', '\udd3b'}, new[] {'\u00a8'},
                new[] {'\u20dc'}, new[] {'\u2250'}, new[] {'\u222f'}, new[] {'\u00a8'},
                new[] {'\u21d3'}, new[] {'\u21d0'}, new[] {'\u21d4'}, new[] {'\u2ae4'},
                new[] {'\u27f8'}, new[] {'\u27fa'}, new[] {'\u27f9'}, new[] {'\u21d2'},
                new[] {'\u22a8'}, new[] {'\u21d1'}, new[] {'\u21d5'}, new[] {'\u2225'},
                new[] {'\u2193'}, new[] {'\u2913'}, new[] {'\u21f5'}, new[] {'\u0311'},
                new[] {'\u2950'}, new[] {'\u295e'}, new[] {'\u21bd'}, new[] {'\u2956'},
                new[] {'\u295f'}, new[] {'\u21c1'}, new[] {'\u2957'}, new[] {'\u22a4'},
                new[] {'\u21a7'}, new[] {'\u21d3'}, new[] {'\ud835', '\udc9f'}, new[] {'\u0110'},
                new[] {'\u014a'}, new[] {'\u00d0'}, new[] {'\u00d0'}, new[] {'\u00c9'},
                new[] {'\u00c9'}, new[] {'\u011a'}, new[] {'\u00ca'}, new[] {'\u00ca'},
                new[] {'\u042d'}, new[] {'\u0116'}, new[] {'\ud835', '\udd08'}, new[] {'\u00c8'},
                new[] {'\u00c8'}, new[] {'\u2208'}, new[] {'\u0112'}, new[] {'\u25fb'},
                new[] {'\u25ab'}, new[] {'\u0118'}, new[] {'\ud835', '\udd3c'}, new[] {'\u0395'},
                new[] {'\u2a75'}, new[] {'\u2242'}, new[] {'\u21cc'}, new[] {'\u2130'},
                new[] {'\u2a73'}, new[] {'\u0397'}, new[] {'\u00cb'}, new[] {'\u00cb'},
                new[] {'\u2203'}, new[] {'\u2147'}, new[] {'\u0424'}, new[] {'\ud835', '\udd09'},
                new[] {'\u25fc'}, new[] {'\u25aa'}, new[] {'\ud835', '\udd3d'}, new[] {'\u2200'},
                new[] {'\u2131'}, new[] {'\u2131'}, new[] {'\u0403'}, new[] {'\u003e'},
                new[] {'\u003e'}, new[] {'\u0393'}, new[] {'\u03dc'}, new[] {'\u011e'},
                new[] {'\u0122'}, new[] {'\u011c'}, new[] {'\u0413'}, new[] {'\u0120'},
                new[] {'\ud835', '\udd0a'}, new[] {'\u22d9'}, new[] {'\ud835', '\udd3e'},
                new[] {'\u2265'}, new[] {'\u22db'}, new[] {'\u2267'}, new[] {'\u2aa2'},
                new[] {'\u2277'}, new[] {'\u2a7e'}, new[] {'\u2273'}, new[] {'\ud835', '\udca2'},
                new[] {'\u226b'}, new[] {'\u042a'}, new[] {'\u02c7'}, new[] {'\u005e'},
                new[] {'\u0124'}, new[] {'\u210c'}, new[] {'\u210b'}, new[] {'\u210d'},
                new[] {'\u2500'}, new[] {'\u210b'}, new[] {'\u0126'}, new[] {'\u224e'},
                new[] {'\u224f'}, new[] {'\u0415'}, new[] {'\u0132'}, new[] {'\u0401'},
                new[] {'\u00cd'}, new[] {'\u00cd'}, new[] {'\u00ce'}, new[] {'\u00ce'},
                new[] {'\u0418'}, new[] {'\u0130'}, new[] {'\u2111'}, new[] {'\u00cc'},
                new[] {'\u00cc'}, new[] {'\u2111'}, new[] {'\u012a'}, new[] {'\u2148'},
                new[] {'\u21d2'}, new[] {'\u222c'}, new[] {'\u222b'}, new[] {'\u22c2'},
                new[] {'\u2063'}, new[] {'\u2062'}, new[] {'\u012e'}, new[] {'\ud835', '\udd40'},
                new[] {'\u0399'}, new[] {'\u2110'}, new[] {'\u0128'}, new[] {'\u0406'},
                new[] {'\u00cf'}, new[] {'\u00cf'}, new[] {'\u0134'}, new[] {'\u0419'},
                new[] {'\ud835', '\udd0d'}, new[] {'\ud835', '\udd41'},
                new[] {'\ud835', '\udca5'}, new[] {'\u0408'}, new[] {'\u0404'}, new[] {'\u0425'},
                new[] {'\u040c'}, new[] {'\u039a'}, new[] {'\u0136'}, new[] {'\u041a'},
                new[] {'\ud835', '\udd0e'}, new[] {'\ud835', '\udd42'},
                new[] {'\ud835', '\udca6'}, new[] {'\u0409'}, new[] {'\u003c'}, new[] {'\u003c'},
                new[] {'\u0139'}, new[] {'\u039b'}, new[] {'\u27ea'}, new[] {'\u2112'},
                new[] {'\u219e'}, new[] {'\u013d'}, new[] {'\u013b'}, new[] {'\u041b'},
                new[] {'\u27e8'}, new[] {'\u2190'}, new[] {'\u21e4'}, new[] {'\u21c6'},
                new[] {'\u2308'}, new[] {'\u27e6'}, new[] {'\u2961'}, new[] {'\u21c3'},
                new[] {'\u2959'}, new[] {'\u230a'}, new[] {'\u2194'}, new[] {'\u294e'},
                new[] {'\u22a3'}, new[] {'\u21a4'}, new[] {'\u295a'}, new[] {'\u22b2'},
                new[] {'\u29cf'}, new[] {'\u22b4'}, new[] {'\u2951'}, new[] {'\u2960'},
                new[] {'\u21bf'}, new[] {'\u2958'}, new[] {'\u21bc'}, new[] {'\u2952'},
                new[] {'\u21d0'}, new[] {'\u21d4'}, new[] {'\u22da'}, new[] {'\u2266'},
                new[] {'\u2276'}, new[] {'\u2aa1'}, new[] {'\u2a7d'}, new[] {'\u2272'},
                new[] {'\ud835', '\udd0f'}, new[] {'\u22d8'}, new[] {'\u21da'}, new[] {'\u013f'},
                new[] {'\u27f5'}, new[] {'\u27f7'}, new[] {'\u27f6'}, new[] {'\u27f8'},
                new[] {'\u27fa'}, new[] {'\u27f9'}, new[] {'\ud835', '\udd43'}, new[] {'\u2199'},
                new[] {'\u2198'}, new[] {'\u2112'}, new[] {'\u21b0'}, new[] {'\u0141'},
                new[] {'\u226a'}, new[] {'\u2905'}, new[] {'\u041c'}, new[] {'\u205f'},
                new[] {'\u2133'}, new[] {'\ud835', '\udd10'}, new[] {'\u2213'},
                new[] {'\ud835', '\udd44'}, new[] {'\u2133'}, new[] {'\u039c'}, new[] {'\u040a'},
                new[] {'\u0143'}, new[] {'\u0147'}, new[] {'\u0145'}, new[] {'\u041d'},
                new[] {'\u200b'}, new[] {'\u200b'}, new[] {'\u200b'}, new[] {'\u200b'},
                new[] {'\u226b'}, new[] {'\u226a'}, new[] {'\n'}, new[] {'\ud835', '\udd11'},
                new[] {'\u2060'}, new[] {'\u00a0'}, new[] {'\u2115'}, new[] {'\u2aec'},
                new[] {'\u2262'}, new[] {'\u226d'}, new[] {'\u2226'}, new[] {'\u2209'},
                new[] {'\u2260'}, new[] {'\u2242', '\u0338'}, new[] {'\u2204'}, new[] {'\u226f'},
                new[] {'\u2271'}, new[] {'\u2267', '\u0338'}, new[] {'\u226b', '\u0338'},
                new[] {'\u2279'}, new[] {'\u2a7e', '\u0338'}, new[] {'\u2275'},
                new[] {'\u224e', '\u0338'}, new[] {'\u224f', '\u0338'}, new[] {'\u22ea'},
                new[] {'\u29cf', '\u0338'}, new[] {'\u22ec'}, new[] {'\u226e'}, new[] {'\u2270'},
                new[] {'\u2278'}, new[] {'\u226a', '\u0338'}, new[] {'\u2a7d', '\u0338'},
                new[] {'\u2274'}, new[] {'\u2aa2', '\u0338'}, new[] {'\u2aa1', '\u0338'},
                new[] {'\u2280'}, new[] {'\u2aaf', '\u0338'}, new[] {'\u22e0'}, new[] {'\u220c'},
                new[] {'\u22eb'}, new[] {'\u29d0', '\u0338'}, new[] {'\u22ed'},
                new[] {'\u228f', '\u0338'}, new[] {'\u22e2'}, new[] {'\u2290', '\u0338'},
                new[] {'\u22e3'}, new[] {'\u2282', '\u20d2'}, new[] {'\u2288'}, new[] {'\u2281'},
                new[] {'\u2ab0', '\u0338'}, new[] {'\u22e1'}, new[] {'\u227f', '\u0338'},
                new[] {'\u2283', '\u20d2'}, new[] {'\u2289'}, new[] {'\u2241'}, new[] {'\u2244'},
                new[] {'\u2247'}, new[] {'\u2249'}, new[] {'\u2224'}, new[] {'\ud835', '\udca9'},
                new[] {'\u00d1'}, new[] {'\u00d1'}, new[] {'\u039d'}, new[] {'\u0152'},
                new[] {'\u00d3'}, new[] {'\u00d3'}, new[] {'\u00d4'}, new[] {'\u00d4'},
                new[] {'\u041e'}, new[] {'\u0150'}, new[] {'\ud835', '\udd12'}, new[] {'\u00d2'},
                new[] {'\u00d2'}, new[] {'\u014c'}, new[] {'\u03a9'}, new[] {'\u039f'},
                new[] {'\ud835', '\udd46'}, new[] {'\u201c'}, new[] {'\u2018'}, new[] {'\u2a54'},
                new[] {'\ud835', '\udcaa'}, new[] {'\u00d8'}, new[] {'\u00d8'}, new[] {'\u00d5'},
                new[] {'\u00d5'}, new[] {'\u2a37'}, new[] {'\u00d6'}, new[] {'\u00d6'},
                new[] {'\u203e'}, new[] {'\u23de'}, new[] {'\u23b4'}, new[] {'\u23dc'},
                new[] {'\u2202'}, new[] {'\u041f'}, new[] {'\ud835', '\udd13'}, new[] {'\u03a6'},
                new[] {'\u03a0'}, new[] {'\u00b1'}, new[] {'\u210c'}, new[] {'\u2119'},
                new[] {'\u2abb'}, new[] {'\u227a'}, new[] {'\u2aaf'}, new[] {'\u227c'},
                new[] {'\u227e'}, new[] {'\u2033'}, new[] {'\u220f'}, new[] {'\u2237'},
                new[] {'\u221d'}, new[] {'\ud835', '\udcab'}, new[] {'\u03a8'}, new[] {'\u0022'},
                new[] {'\u0022'}, new[] {'\ud835', '\udd14'}, new[] {'\u211a'},
                new[] {'\ud835', '\udcac'}, new[] {'\u2910'}, new[] {'\u00ae'}, new[] {'\u00ae'},
                new[] {'\u0154'}, new[] {'\u27eb'}, new[] {'\u21a0'}, new[] {'\u2916'},
                new[] {'\u0158'}, new[] {'\u0156'}, new[] {'\u0420'}, new[] {'\u211c'},
                new[] {'\u220b'}, new[] {'\u21cb'}, new[] {'\u296f'}, new[] {'\u211c'},
                new[] {'\u03a1'}, new[] {'\u27e9'}, new[] {'\u2192'}, new[] {'\u21e5'},
                new[] {'\u21c4'}, new[] {'\u2309'}, new[] {'\u27e7'}, new[] {'\u295d'},
                new[] {'\u21c2'}, new[] {'\u2955'}, new[] {'\u230b'}, new[] {'\u22a2'},
                new[] {'\u21a6'}, new[] {'\u295b'}, new[] {'\u22b3'}, new[] {'\u29d0'},
                new[] {'\u22b5'}, new[] {'\u294f'}, new[] {'\u295c'}, new[] {'\u21be'},
                new[] {'\u2954'}, new[] {'\u21c0'}, new[] {'\u2953'}, new[] {'\u21d2'},
                new[] {'\u211d'}, new[] {'\u2970'}, new[] {'\u21db'}, new[] {'\u211b'},
                new[] {'\u21b1'}, new[] {'\u29f4'}, new[] {'\u0429'}, new[] {'\u0428'},
                new[] {'\u042c'}, new[] {'\u015a'}, new[] {'\u2abc'}, new[] {'\u0160'},
                new[] {'\u015e'}, new[] {'\u015c'}, new[] {'\u0421'}, new[] {'\ud835', '\udd16'},
                new[] {'\u2193'}, new[] {'\u2190'}, new[] {'\u2192'}, new[] {'\u2191'},
                new[] {'\u03a3'}, new[] {'\u2218'}, new[] {'\ud835', '\udd4a'}, new[] {'\u221a'},
                new[] {'\u25a1'}, new[] {'\u2293'}, new[] {'\u228f'}, new[] {'\u2291'},
                new[] {'\u2290'}, new[] {'\u2292'}, new[] {'\u2294'}, new[] {'\ud835', '\udcae'},
                new[] {'\u22c6'}, new[] {'\u22d0'}, new[] {'\u22d0'}, new[] {'\u2286'},
                new[] {'\u227b'}, new[] {'\u2ab0'}, new[] {'\u227d'}, new[] {'\u227f'},
                new[] {'\u220b'}, new[] {'\u2211'}, new[] {'\u22d1'}, new[] {'\u2283'},
                new[] {'\u2287'}, new[] {'\u22d1'}, new[] {'\u00de'}, new[] {'\u00de'},
                new[] {'\u2122'}, new[] {'\u040b'}, new[] {'\u0426'}, new[] {'\u0009'},
                new[] {'\u03a4'}, new[] {'\u0164'}, new[] {'\u0162'}, new[] {'\u0422'},
                new[] {'\ud835', '\udd17'}, new[] {'\u2234'}, new[] {'\u0398'},
                new[] {'\u205f', '\u200a'}, new[] {'\u2009'}, new[] {'\u223c'}, new[] {'\u2243'},
                new[] {'\u2245'}, new[] {'\u2248'}, new[] {'\ud835', '\udd4b'}, new[] {'\u20db'},
                new[] {'\ud835', '\udcaf'}, new[] {'\u0166'}, new[] {'\u00da'}, new[] {'\u00da'},
                new[] {'\u219f'}, new[] {'\u2949'}, new[] {'\u040e'}, new[] {'\u016c'},
                new[] {'\u00db'}, new[] {'\u00db'}, new[] {'\u0423'}, new[] {'\u0170'},
                new[] {'\ud835', '\udd18'}, new[] {'\u00d9'}, new[] {'\u00d9'}, new[] {'\u016a'},
                new[] {'\u005f'}, new[] {'\u23df'}, new[] {'\u23b5'}, new[] {'\u23dd'},
                new[] {'\u22c3'}, new[] {'\u228e'}, new[] {'\u0172'}, new[] {'\ud835', '\udd4c'},
                new[] {'\u2191'}, new[] {'\u2912'}, new[] {'\u21c5'}, new[] {'\u2195'},
                new[] {'\u296e'}, new[] {'\u22a5'}, new[] {'\u21a5'}, new[] {'\u21d1'},
                new[] {'\u21d5'}, new[] {'\u2196'}, new[] {'\u2197'}, new[] {'\u03d2'},
                new[] {'\u03a5'}, new[] {'\u016e'}, new[] {'\ud835', '\udcb0'}, new[] {'\u0168'},
                new[] {'\u00dc'}, new[] {'\u00dc'}, new[] {'\u22ab'}, new[] {'\u2aeb'},
                new[] {'\u0412'}, new[] {'\u22a9'}, new[] {'\u2ae6'}, new[] {'\u22c1'},
                new[] {'\u2016'}, new[] {'\u2016'}, new[] {'\u2223'}, new[] {'\u007c'},
                new[] {'\u2758'}, new[] {'\u2240'}, new[] {'\u200a'}, new[] {'\ud835', '\udd19'},
                new[] {'\ud835', '\udd4d'}, new[] {'\ud835', '\udcb1'}, new[] {'\u22aa'},
                new[] {'\u0174'}, new[] {'\u22c0'}, new[] {'\ud835', '\udd1a'},
                new[] {'\ud835', '\udd4e'}, new[] {'\ud835', '\udcb2'},
                new[] {'\ud835', '\udd1b'}, new[] {'\u039e'}, new[] {'\ud835', '\udd4f'},
                new[] {'\ud835', '\udcb3'}, new[] {'\u042f'}, new[] {'\u0407'}, new[] {'\u042e'},
                new[] {'\u00dd'}, new[] {'\u00dd'}, new[] {'\u0176'}, new[] {'\u042b'},
                new[] {'\ud835', '\udd1c'}, new[] {'\ud835', '\udd50'},
                new[] {'\ud835', '\udcb4'}, new[] {'\u0178'}, new[] {'\u0416'}, new[] {'\u0179'},
                new[] {'\u017d'}, new[] {'\u0417'}, new[] {'\u017b'}, new[] {'\u200b'},
                new[] {'\u0396'}, new[] {'\u2128'}, new[] {'\u2124'}, new[] {'\ud835', '\udcb5'},
                new[] {'\u00e1'}, new[] {'\u00e1'}, new[] {'\u0103'}, new[] {'\u223e'},
                new[] {'\u223e', '\u0333'}, new[] {'\u223f'}, new[] {'\u00e2'}, new[] {'\u00e2'},
                new[] {'\u00b4'}, new[] {'\u00b4'}, new[] {'\u0430'}, new[] {'\u00e6'},
                new[] {'\u00e6'}, new[] {'\u2061'}, new[] {'\ud835', '\udd1e'}, new[] {'\u00e0'},
                new[] {'\u00e0'}, new[] {'\u2135'}, new[] {'\u2135'}, new[] {'\u03b1'},
                new[] {'\u0101'}, new[] {'\u2a3f'}, new[] {'\u0026'}, new[] {'\u0026'},
                new[] {'\u2227'}, new[] {'\u2a55'}, new[] {'\u2a5c'}, new[] {'\u2a58'},
                new[] {'\u2a5a'}, new[] {'\u2220'}, new[] {'\u29a4'}, new[] {'\u2220'},
                new[] {'\u2221'}, new[] {'\u29a8'}, new[] {'\u29a9'}, new[] {'\u29aa'},
                new[] {'\u29ab'}, new[] {'\u29ac'}, new[] {'\u29ad'}, new[] {'\u29ae'},
                new[] {'\u29af'}, new[] {'\u221f'}, new[] {'\u22be'}, new[] {'\u299d'},
                new[] {'\u2222'}, new[] {'\u00c5'}, new[] {'\u237c'}, new[] {'\u0105'},
                new[] {'\ud835', '\udd52'}, new[] {'\u2248'}, new[] {'\u2a70'}, new[] {'\u2a6f'},
                new[] {'\u224a'}, new[] {'\u224b'}, new[] {'\''}, new[] {'\u2248'},
                new[] {'\u224a'},
                new[] {'\u00e5'}, new[] {'\u00e5'}, new[] {'\ud835', '\udcb6'}, new[] {'\u002a'},
                new[] {'\u2248'}, new[] {'\u224d'}, new[] {'\u00e3'}, new[] {'\u00e3'},
                new[] {'\u00e4'}, new[] {'\u00e4'}, new[] {'\u2233'}, new[] {'\u2a11'},
                new[] {'\u2aed'}, new[] {'\u224c'}, new[] {'\u03f6'}, new[] {'\u2035'},
                new[] {'\u223d'}, new[] {'\u22cd'}, new[] {'\u22bd'}, new[] {'\u2305'},
                new[] {'\u2305'}, new[] {'\u23b5'}, new[] {'\u23b6'}, new[] {'\u224c'},
                new[] {'\u0431'}, new[] {'\u201e'}, new[] {'\u2235'}, new[] {'\u2235'},
                new[] {'\u29b0'}, new[] {'\u03f6'}, new[] {'\u212c'}, new[] {'\u03b2'},
                new[] {'\u2136'}, new[] {'\u226c'}, new[] {'\ud835', '\udd1f'}, new[] {'\u22c2'},
                new[] {'\u25ef'}, new[] {'\u22c3'}, new[] {'\u2a00'}, new[] {'\u2a01'},
                new[] {'\u2a02'}, new[] {'\u2a06'}, new[] {'\u2605'}, new[] {'\u25bd'},
                new[] {'\u25b3'}, new[] {'\u2a04'}, new[] {'\u22c1'}, new[] {'\u22c0'},
                new[] {'\u290d'}, new[] {'\u29eb'}, new[] {'\u25aa'}, new[] {'\u25b4'},
                new[] {'\u25be'}, new[] {'\u25c2'}, new[] {'\u25b8'}, new[] {'\u2423'},
                new[] {'\u2592'}, new[] {'\u2591'}, new[] {'\u2593'}, new[] {'\u2588'},
                new[] {'\u003d', '\u20e5'}, new[] {'\u2261', '\u20e5'}, new[] {'\u2310'},
                new[] {'\ud835', '\udd53'}, new[] {'\u22a5'}, new[] {'\u22a5'}, new[] {'\u22c8'},
                new[] {'\u2557'}, new[] {'\u2554'}, new[] {'\u2556'}, new[] {'\u2553'},
                new[] {'\u2550'}, new[] {'\u2566'}, new[] {'\u2569'}, new[] {'\u2564'},
                new[] {'\u2567'}, new[] {'\u255d'}, new[] {'\u255a'}, new[] {'\u255c'},
                new[] {'\u2559'}, new[] {'\u2551'}, new[] {'\u256c'}, new[] {'\u2563'},
                new[] {'\u2560'}, new[] {'\u256b'}, new[] {'\u2562'}, new[] {'\u255f'},
                new[] {'\u29c9'}, new[] {'\u2555'}, new[] {'\u2552'}, new[] {'\u2510'},
                new[] {'\u250c'}, new[] {'\u2500'}, new[] {'\u2565'}, new[] {'\u2568'},
                new[] {'\u252c'}, new[] {'\u2534'}, new[] {'\u229f'}, new[] {'\u229e'},
                new[] {'\u22a0'}, new[] {'\u255b'}, new[] {'\u2558'}, new[] {'\u2518'},
                new[] {'\u2514'}, new[] {'\u2502'}, new[] {'\u256a'}, new[] {'\u2561'},
                new[] {'\u255e'}, new[] {'\u253c'}, new[] {'\u2524'}, new[] {'\u251c'},
                new[] {'\u2035'}, new[] {'\u02d8'}, new[] {'\u00a6'}, new[] {'\u00a6'},
                new[] {'\ud835', '\udcb7'}, new[] {'\u204f'}, new[] {'\u223d'}, new[] {'\u22cd'},
                new[] {'\\'}, new[] {'\u29c5'}, new[] {'\u27c8'}, new[] {'\u2022'},
                new[] {'\u2022'},
                new[] {'\u224e'}, new[] {'\u2aae'}, new[] {'\u224f'}, new[] {'\u224f'},
                new[] {'\u0107'}, new[] {'\u2229'}, new[] {'\u2a44'}, new[] {'\u2a49'},
                new[] {'\u2a4b'}, new[] {'\u2a47'}, new[] {'\u2a40'}, new[] {'\u2229', '\ufe00'},
                new[] {'\u2041'}, new[] {'\u02c7'}, new[] {'\u2a4d'}, new[] {'\u010d'},
                new[] {'\u00e7'}, new[] {'\u00e7'}, new[] {'\u0109'}, new[] {'\u2a4c'},
                new[] {'\u2a50'}, new[] {'\u010b'}, new[] {'\u00b8'}, new[] {'\u00b8'},
                new[] {'\u29b2'}, new[] {'\u00a2'}, new[] {'\u00a2'}, new[] {'\u00b7'},
                new[] {'\ud835', '\udd20'}, new[] {'\u0447'}, new[] {'\u2713'}, new[] {'\u2713'},
                new[] {'\u03c7'}, new[] {'\u25cb'}, new[] {'\u29c3'}, new[] {'\u02c6'},
                new[] {'\u2257'}, new[] {'\u21ba'}, new[] {'\u21bb'}, new[] {'\u00ae'},
                new[] {'\u24c8'}, new[] {'\u229b'}, new[] {'\u229a'}, new[] {'\u229d'},
                new[] {'\u2257'}, new[] {'\u2a10'}, new[] {'\u2aef'}, new[] {'\u29c2'},
                new[] {'\u2663'}, new[] {'\u2663'}, new[] {'\u003a'}, new[] {'\u2254'},
                new[] {'\u2254'}, new[] {'\u002c'}, new[] {'\u0040'}, new[] {'\u2201'},
                new[] {'\u2218'}, new[] {'\u2201'}, new[] {'\u2102'}, new[] {'\u2245'},
                new[] {'\u2a6d'}, new[] {'\u222e'}, new[] {'\ud835', '\udd54'}, new[] {'\u2210'},
                new[] {'\u00a9'}, new[] {'\u00a9'}, new[] {'\u2117'}, new[] {'\u21b5'},
                new[] {'\u2717'}, new[] {'\ud835', '\udcb8'}, new[] {'\u2acf'}, new[] {'\u2ad1'},
                new[] {'\u2ad0'}, new[] {'\u2ad2'}, new[] {'\u22ef'}, new[] {'\u2938'},
                new[] {'\u2935'}, new[] {'\u22de'}, new[] {'\u22df'}, new[] {'\u21b6'},
                new[] {'\u293d'}, new[] {'\u222a'}, new[] {'\u2a48'}, new[] {'\u2a46'},
                new[] {'\u2a4a'}, new[] {'\u228d'}, new[] {'\u2a45'}, new[] {'\u222a', '\ufe00'},
                new[] {'\u21b7'}, new[] {'\u293c'}, new[] {'\u22de'}, new[] {'\u22df'},
                new[] {'\u22ce'}, new[] {'\u22cf'}, new[] {'\u00a4'}, new[] {'\u00a4'},
                new[] {'\u21b6'}, new[] {'\u21b7'}, new[] {'\u22ce'}, new[] {'\u22cf'},
                new[] {'\u2232'}, new[] {'\u2231'}, new[] {'\u232d'}, new[] {'\u21d3'},
                new[] {'\u2965'}, new[] {'\u2020'}, new[] {'\u2138'}, new[] {'\u2193'},
                new[] {'\u2010'}, new[] {'\u22a3'}, new[] {'\u290f'}, new[] {'\u02dd'},
                new[] {'\u010f'}, new[] {'\u0434'}, new[] {'\u2146'}, new[] {'\u2021'},
                new[] {'\u21ca'}, new[] {'\u2a77'}, new[] {'\u00b0'}, new[] {'\u00b0'},
                new[] {'\u03b4'}, new[] {'\u29b1'}, new[] {'\u297f'}, new[] {'\ud835', '\udd21'},
                new[] {'\u21c3'}, new[] {'\u21c2'}, new[] {'\u22c4'}, new[] {'\u22c4'},
                new[] {'\u2666'}, new[] {'\u2666'}, new[] {'\u00a8'}, new[] {'\u03dd'},
                new[] {'\u22f2'}, new[] {'\u00f7'}, new[] {'\u00f7'}, new[] {'\u00f7'},
                new[] {'\u22c7'}, new[] {'\u22c7'}, new[] {'\u0452'}, new[] {'\u231e'},
                new[] {'\u230d'}, new[] {'\u0024'}, new[] {'\ud835', '\udd55'}, new[] {'\u02d9'},
                new[] {'\u2250'}, new[] {'\u2251'}, new[] {'\u2238'}, new[] {'\u2214'},
                new[] {'\u22a1'}, new[] {'\u2306'}, new[] {'\u2193'}, new[] {'\u21ca'},
                new[] {'\u21c3'}, new[] {'\u21c2'}, new[] {'\u2910'}, new[] {'\u231f'},
                new[] {'\u230c'}, new[] {'\ud835', '\udcb9'}, new[] {'\u0455'}, new[] {'\u29f6'},
                new[] {'\u0111'}, new[] {'\u22f1'}, new[] {'\u25bf'}, new[] {'\u25be'},
                new[] {'\u21f5'}, new[] {'\u296f'}, new[] {'\u29a6'}, new[] {'\u045f'},
                new[] {'\u27ff'}, new[] {'\u2a77'}, new[] {'\u2251'}, new[] {'\u00e9'},
                new[] {'\u00e9'}, new[] {'\u2a6e'}, new[] {'\u011b'}, new[] {'\u2256'},
                new[] {'\u00ea'}, new[] {'\u00ea'}, new[] {'\u2255'}, new[] {'\u044d'},
                new[] {'\u0117'}, new[] {'\u2147'}, new[] {'\u2252'}, new[] {'\ud835', '\udd22'},
                new[] {'\u2a9a'}, new[] {'\u00e8'}, new[] {'\u00e8'}, new[] {'\u2a96'},
                new[] {'\u2a98'}, new[] {'\u2a99'}, new[] {'\u23e7'}, new[] {'\u2113'},
                new[] {'\u2a95'}, new[] {'\u2a97'}, new[] {'\u0113'}, new[] {'\u2205'},
                new[] {'\u2205'}, new[] {'\u2205'}, new[] {'\u2004'}, new[] {'\u2005'},
                new[] {'\u2003'}, new[] {'\u014b'}, new[] {'\u2002'}, new[] {'\u0119'},
                new[] {'\ud835', '\udd56'}, new[] {'\u22d5'}, new[] {'\u29e3'}, new[] {'\u2a71'},
                new[] {'\u03b5'}, new[] {'\u03b5'}, new[] {'\u03f5'}, new[] {'\u2256'},
                new[] {'\u2255'}, new[] {'\u2242'}, new[] {'\u2a96'}, new[] {'\u2a95'},
                new[] {'\u003d'}, new[] {'\u225f'}, new[] {'\u2261'}, new[] {'\u2a78'},
                new[] {'\u29e5'}, new[] {'\u2253'}, new[] {'\u2971'}, new[] {'\u212f'},
                new[] {'\u2250'}, new[] {'\u2242'}, new[] {'\u03b7'}, new[] {'\u00f0'},
                new[] {'\u00f0'}, new[] {'\u00eb'}, new[] {'\u00eb'}, new[] {'\u20ac'},
                new[] {'\u0021'}, new[] {'\u2203'}, new[] {'\u2130'}, new[] {'\u2147'},
                new[] {'\u2252'}, new[] {'\u0444'}, new[] {'\u2640'}, new[] {'\ufb03'},
                new[] {'\ufb00'}, new[] {'\ufb04'}, new[] {'\ud835', '\udd23'}, new[] {'\ufb01'},
                new[] {'\u0066', '\u006a'}, new[] {'\u266d'}, new[] {'\ufb02'}, new[] {'\u25b1'},
                new[] {'\u0192'}, new[] {'\ud835', '\udd57'}, new[] {'\u2200'}, new[] {'\u22d4'},
                new[] {'\u2ad9'}, new[] {'\u2a0d'}, new[] {'\u00bd'}, new[] {'\u00bd'},
                new[] {'\u2153'}, new[] {'\u00bc'}, new[] {'\u00bc'}, new[] {'\u2155'},
                new[] {'\u2159'}, new[] {'\u215b'}, new[] {'\u2154'}, new[] {'\u2156'},
                new[] {'\u00be'}, new[] {'\u00be'}, new[] {'\u2157'}, new[] {'\u215c'},
                new[] {'\u2158'}, new[] {'\u215a'}, new[] {'\u215d'}, new[] {'\u215e'},
                new[] {'\u2044'}, new[] {'\u2322'}, new[] {'\ud835', '\udcbb'}, new[] {'\u2267'},
                new[] {'\u2a8c'}, new[] {'\u01f5'}, new[] {'\u03b3'}, new[] {'\u03dd'},
                new[] {'\u2a86'}, new[] {'\u011f'}, new[] {'\u011d'}, new[] {'\u0433'},
                new[] {'\u0121'}, new[] {'\u2265'}, new[] {'\u22db'}, new[] {'\u2265'},
                new[] {'\u2267'}, new[] {'\u2a7e'}, new[] {'\u2a7e'}, new[] {'\u2aa9'},
                new[] {'\u2a80'}, new[] {'\u2a82'}, new[] {'\u2a84'}, new[] {'\u22db', '\ufe00'},
                new[] {'\u2a94'}, new[] {'\ud835', '\udd24'}, new[] {'\u226b'}, new[] {'\u22d9'},
                new[] {'\u2137'}, new[] {'\u0453'}, new[] {'\u2277'}, new[] {'\u2a92'},
                new[] {'\u2aa5'}, new[] {'\u2aa4'}, new[] {'\u2269'}, new[] {'\u2a8a'},
                new[] {'\u2a8a'}, new[] {'\u2a88'}, new[] {'\u2a88'}, new[] {'\u2269'},
                new[] {'\u22e7'}, new[] {'\ud835', '\udd58'}, new[] {'\u0060'}, new[] {'\u210a'},
                new[] {'\u2273'}, new[] {'\u2a8e'}, new[] {'\u2a90'}, new[] {'\u003e'},
                new[] {'\u003e'}, new[] {'\u2aa7'}, new[] {'\u2a7a'}, new[] {'\u22d7'},
                new[] {'\u2995'}, new[] {'\u2a7c'}, new[] {'\u2a86'}, new[] {'\u2978'},
                new[] {'\u22d7'}, new[] {'\u22db'}, new[] {'\u2a8c'}, new[] {'\u2277'},
                new[] {'\u2273'}, new[] {'\u2269', '\ufe00'}, new[] {'\u2269', '\ufe00'},
                new[] {'\u21d4'}, new[] {'\u200a'}, new[] {'\u00bd'}, new[] {'\u210b'},
                new[] {'\u044a'}, new[] {'\u2194'}, new[] {'\u2948'}, new[] {'\u21ad'},
                new[] {'\u210f'}, new[] {'\u0125'}, new[] {'\u2665'}, new[] {'\u2665'},
                new[] {'\u2026'}, new[] {'\u22b9'}, new[] {'\ud835', '\udd25'}, new[] {'\u2925'},
                new[] {'\u2926'}, new[] {'\u21ff'}, new[] {'\u223b'}, new[] {'\u21a9'},
                new[] {'\u21aa'}, new[] {'\ud835', '\udd59'}, new[] {'\u2015'},
                new[] {'\ud835', '\udcbd'}, new[] {'\u210f'}, new[] {'\u0127'}, new[] {'\u2043'},
                new[] {'\u2010'}, new[] {'\u00ed'}, new[] {'\u00ed'}, new[] {'\u2063'},
                new[] {'\u00ee'}, new[] {'\u00ee'}, new[] {'\u0438'}, new[] {'\u0435'},
                new[] {'\u00a1'}, new[] {'\u00a1'}, new[] {'\u21d4'}, new[] {'\ud835', '\udd26'},
                new[] {'\u00ec'}, new[] {'\u00ec'}, new[] {'\u2148'}, new[] {'\u2a0c'},
                new[] {'\u222d'}, new[] {'\u29dc'}, new[] {'\u2129'}, new[] {'\u0133'},
                new[] {'\u012b'}, new[] {'\u2111'}, new[] {'\u2110'}, new[] {'\u2111'},
                new[] {'\u0131'}, new[] {'\u22b7'}, new[] {'\u01b5'}, new[] {'\u2208'},
                new[] {'\u2105'}, new[] {'\u221e'}, new[] {'\u29dd'}, new[] {'\u0131'},
                new[] {'\u222b'}, new[] {'\u22ba'}, new[] {'\u2124'}, new[] {'\u22ba'},
                new[] {'\u2a17'}, new[] {'\u2a3c'}, new[] {'\u0451'}, new[] {'\u012f'},
                new[] {'\ud835', '\udd5a'}, new[] {'\u03b9'}, new[] {'\u2a3c'}, new[] {'\u00bf'},
                new[] {'\u00bf'}, new[] {'\ud835', '\udcbe'}, new[] {'\u2208'}, new[] {'\u22f9'},
                new[] {'\u22f5'}, new[] {'\u22f4'}, new[] {'\u22f3'}, new[] {'\u2208'},
                new[] {'\u2062'}, new[] {'\u0129'}, new[] {'\u0456'}, new[] {'\u00ef'},
                new[] {'\u00ef'}, new[] {'\u0135'}, new[] {'\u0439'}, new[] {'\ud835', '\udd27'},
                new[] {'\u0237'}, new[] {'\ud835', '\udd5b'}, new[] {'\ud835', '\udcbf'},
                new[] {'\u0458'}, new[] {'\u0454'}, new[] {'\u03ba'}, new[] {'\u03f0'},
                new[] {'\u0137'}, new[] {'\u043a'}, new[] {'\ud835', '\udd28'}, new[] {'\u0138'},
                new[] {'\u0445'}, new[] {'\u045c'}, new[] {'\ud835', '\udd5c'},
                new[] {'\ud835', '\udcc0'}, new[] {'\u21da'}, new[] {'\u21d0'}, new[] {'\u291b'},
                new[] {'\u290e'}, new[] {'\u2266'}, new[] {'\u2a8b'}, new[] {'\u2962'},
                new[] {'\u013a'}, new[] {'\u29b4'}, new[] {'\u2112'}, new[] {'\u03bb'},
                new[] {'\u27e8'}, new[] {'\u2991'}, new[] {'\u27e8'}, new[] {'\u2a85'},
                new[] {'\u00ab'}, new[] {'\u00ab'}, new[] {'\u2190'}, new[] {'\u21e4'},
                new[] {'\u291f'}, new[] {'\u291d'}, new[] {'\u21a9'}, new[] {'\u21ab'},
                new[] {'\u2939'}, new[] {'\u2973'}, new[] {'\u21a2'}, new[] {'\u2aab'},
                new[] {'\u2919'}, new[] {'\u2aad'}, new[] {'\u2aad', '\ufe00'}, new[] {'\u290c'},
                new[] {'\u2772'}, new[] {'\u007b'}, new[] {'\u005b'}, new[] {'\u298b'},
                new[] {'\u298f'}, new[] {'\u298d'}, new[] {'\u013e'}, new[] {'\u013c'},
                new[] {'\u2308'}, new[] {'\u007b'}, new[] {'\u043b'}, new[] {'\u2936'},
                new[] {'\u201c'}, new[] {'\u201e'}, new[] {'\u2967'}, new[] {'\u294b'},
                new[] {'\u21b2'}, new[] {'\u2264'}, new[] {'\u2190'}, new[] {'\u21a2'},
                new[] {'\u21bd'}, new[] {'\u21bc'}, new[] {'\u21c7'}, new[] {'\u2194'},
                new[] {'\u21c6'}, new[] {'\u21cb'}, new[] {'\u21ad'}, new[] {'\u22cb'},
                new[] {'\u22da'}, new[] {'\u2264'}, new[] {'\u2266'}, new[] {'\u2a7d'},
                new[] {'\u2a7d'}, new[] {'\u2aa8'}, new[] {'\u2a7f'}, new[] {'\u2a81'},
                new[] {'\u2a83'}, new[] {'\u22da', '\ufe00'}, new[] {'\u2a93'}, new[] {'\u2a85'},
                new[] {'\u22d6'}, new[] {'\u22da'}, new[] {'\u2a8b'}, new[] {'\u2276'},
                new[] {'\u2272'}, new[] {'\u297c'}, new[] {'\u230a'}, new[] {'\ud835', '\udd29'},
                new[] {'\u2276'}, new[] {'\u2a91'}, new[] {'\u21bd'}, new[] {'\u21bc'},
                new[] {'\u296a'}, new[] {'\u2584'}, new[] {'\u0459'}, new[] {'\u226a'},
                new[] {'\u21c7'}, new[] {'\u231e'}, new[] {'\u296b'}, new[] {'\u25fa'},
                new[] {'\u0140'}, new[] {'\u23b0'}, new[] {'\u23b0'}, new[] {'\u2268'},
                new[] {'\u2a89'}, new[] {'\u2a89'}, new[] {'\u2a87'}, new[] {'\u2a87'},
                new[] {'\u2268'}, new[] {'\u22e6'}, new[] {'\u27ec'}, new[] {'\u21fd'},
                new[] {'\u27e6'}, new[] {'\u27f5'}, new[] {'\u27f7'}, new[] {'\u27fc'},
                new[] {'\u27f6'}, new[] {'\u21ab'}, new[] {'\u21ac'}, new[] {'\u2985'},
                new[] {'\ud835', '\udd5d'}, new[] {'\u2a2d'}, new[] {'\u2a34'}, new[] {'\u2217'},
                new[] {'\u005f'}, new[] {'\u25ca'}, new[] {'\u25ca'}, new[] {'\u29eb'},
                new[] {'\u0028'}, new[] {'\u2993'}, new[] {'\u21c6'}, new[] {'\u231f'},
                new[] {'\u21cb'}, new[] {'\u296d'}, new[] {'\u200e'}, new[] {'\u22bf'},
                new[] {'\u2039'}, new[] {'\ud835', '\udcc1'}, new[] {'\u21b0'}, new[] {'\u2272'},
                new[] {'\u2a8d'}, new[] {'\u2a8f'}, new[] {'\u005b'}, new[] {'\u2018'},
                new[] {'\u201a'}, new[] {'\u0142'}, new[] {'\u003c'}, new[] {'\u003c'},
                new[] {'\u2aa6'}, new[] {'\u2a79'}, new[] {'\u22d6'}, new[] {'\u22cb'},
                new[] {'\u22c9'}, new[] {'\u2976'}, new[] {'\u2a7b'}, new[] {'\u2996'},
                new[] {'\u25c3'}, new[] {'\u22b4'}, new[] {'\u25c2'}, new[] {'\u294a'},
                new[] {'\u2966'}, new[] {'\u2268', '\ufe00'}, new[] {'\u2268', '\ufe00'},
                new[] {'\u223a'}, new[] {'\u00af'}, new[] {'\u00af'}, new[] {'\u2642'},
                new[] {'\u2720'}, new[] {'\u2720'}, new[] {'\u21a6'}, new[] {'\u21a6'},
                new[] {'\u21a7'}, new[] {'\u21a4'}, new[] {'\u21a5'}, new[] {'\u25ae'},
                new[] {'\u2a29'}, new[] {'\u043c'}, new[] {'\u2014'}, new[] {'\u2221'},
                new[] {'\ud835', '\udd2a'}, new[] {'\u2127'}, new[] {'\u00b5'}, new[] {'\u00b5'},
                new[] {'\u2223'}, new[] {'\u002a'}, new[] {'\u2af0'}, new[] {'\u00b7'},
                new[] {'\u00b7'}, new[] {'\u2212'}, new[] {'\u229f'}, new[] {'\u2238'},
                new[] {'\u2a2a'}, new[] {'\u2adb'}, new[] {'\u2026'}, new[] {'\u2213'},
                new[] {'\u22a7'}, new[] {'\ud835', '\udd5e'}, new[] {'\u2213'},
                new[] {'\ud835', '\udcc2'}, new[] {'\u223e'}, new[] {'\u03bc'}, new[] {'\u22b8'},
                new[] {'\u22b8'}, new[] {'\u22d9', '\u0338'}, new[] {'\u226b', '\u20d2'},
                new[] {'\u226b', '\u0338'}, new[] {'\u21cd'}, new[] {'\u21ce'},
                new[] {'\u22d8', '\u0338'}, new[] {'\u226a', '\u20d2'},
                new[] {'\u226a', '\u0338'}, new[] {'\u21cf'}, new[] {'\u22af'}, new[] {'\u22ae'},
                new[] {'\u2207'}, new[] {'\u0144'}, new[] {'\u2220', '\u20d2'}, new[] {'\u2249'},
                new[] {'\u2a70', '\u0338'}, new[] {'\u224b', '\u0338'}, new[] {'\u0149'},
                new[] {'\u2249'}, new[] {'\u266e'}, new[] {'\u266e'}, new[] {'\u2115'},
                new[] {'\u00a0'}, new[] {'\u00a0'}, new[] {'\u224e', '\u0338'},
                new[] {'\u224f', '\u0338'}, new[] {'\u2a43'}, new[] {'\u0148'}, new[] {'\u0146'},
                new[] {'\u2247'}, new[] {'\u2a6d', '\u0338'}, new[] {'\u2a42'}, new[] {'\u043d'},
                new[] {'\u2013'}, new[] {'\u2260'}, new[] {'\u21d7'}, new[] {'\u2924'},
                new[] {'\u2197'}, new[] {'\u2197'}, new[] {'\u2250', '\u0338'}, new[] {'\u2262'},
                new[] {'\u2928'}, new[] {'\u2242', '\u0338'}, new[] {'\u2204'}, new[] {'\u2204'},
                new[] {'\ud835', '\udd2b'}, new[] {'\u2267', '\u0338'}, new[] {'\u2271'},
                new[] {'\u2271'}, new[] {'\u2267', '\u0338'}, new[] {'\u2a7e', '\u0338'},
                new[] {'\u2a7e', '\u0338'}, new[] {'\u2275'}, new[] {'\u226f'}, new[] {'\u226f'},
                new[] {'\u21ce'}, new[] {'\u21ae'}, new[] {'\u2af2'}, new[] {'\u220b'},
                new[] {'\u22fc'}, new[] {'\u22fa'}, new[] {'\u220b'}, new[] {'\u045a'},
                new[] {'\u21cd'}, new[] {'\u2266', '\u0338'}, new[] {'\u219a'}, new[] {'\u2025'},
                new[] {'\u2270'}, new[] {'\u219a'}, new[] {'\u21ae'}, new[] {'\u2270'},
                new[] {'\u2266', '\u0338'}, new[] {'\u2a7d', '\u0338'},
                new[] {'\u2a7d', '\u0338'}, new[] {'\u226e'}, new[] {'\u2274'}, new[] {'\u226e'},
                new[] {'\u22ea'}, new[] {'\u22ec'}, new[] {'\u2224'}, new[] {'\ud835', '\udd5f'},
                new[] {'\u00ac'}, new[] {'\u00ac'}, new[] {'\u2209'}, new[] {'\u22f9', '\u0338'},
                new[] {'\u22f5', '\u0338'}, new[] {'\u2209'}, new[] {'\u22f7'}, new[] {'\u22f6'},
                new[] {'\u220c'}, new[] {'\u220c'}, new[] {'\u22fe'}, new[] {'\u22fd'},
                new[] {'\u2226'}, new[] {'\u2226'}, new[] {'\u2afd', '\u20e5'},
                new[] {'\u2202', '\u0338'}, new[] {'\u2a14'}, new[] {'\u2280'}, new[] {'\u22e0'},
                new[] {'\u2aaf', '\u0338'}, new[] {'\u2280'}, new[] {'\u2aaf', '\u0338'},
                new[] {'\u21cf'}, new[] {'\u219b'}, new[] {'\u2933', '\u0338'},
                new[] {'\u219d', '\u0338'}, new[] {'\u219b'}, new[] {'\u22eb'}, new[] {'\u22ed'},
                new[] {'\u2281'}, new[] {'\u22e1'}, new[] {'\u2ab0', '\u0338'},
                new[] {'\ud835', '\udcc3'}, new[] {'\u2224'}, new[] {'\u2226'}, new[] {'\u2241'},
                new[] {'\u2244'}, new[] {'\u2244'}, new[] {'\u2224'}, new[] {'\u2226'},
                new[] {'\u22e2'}, new[] {'\u22e3'}, new[] {'\u2284'}, new[] {'\u2ac5', '\u0338'},
                new[] {'\u2288'}, new[] {'\u2282', '\u20d2'}, new[] {'\u2288'},
                new[] {'\u2ac5', '\u0338'}, new[] {'\u2281'}, new[] {'\u2ab0', '\u0338'},
                new[] {'\u2285'}, new[] {'\u2ac6', '\u0338'}, new[] {'\u2289'},
                new[] {'\u2283', '\u20d2'}, new[] {'\u2289'}, new[] {'\u2ac6', '\u0338'},
                new[] {'\u2279'}, new[] {'\u00f1'}, new[] {'\u00f1'}, new[] {'\u2278'},
                new[] {'\u22ea'}, new[] {'\u22ec'}, new[] {'\u22eb'}, new[] {'\u22ed'},
                new[] {'\u03bd'}, new[] {'\u0023'}, new[] {'\u2116'}, new[] {'\u2007'},
                new[] {'\u22ad'}, new[] {'\u2904'}, new[] {'\u224d', '\u20d2'}, new[] {'\u22ac'},
                new[] {'\u2265', '\u20d2'}, new[] {'\u003e', '\u20d2'}, new[] {'\u29de'},
                new[] {'\u2902'}, new[] {'\u2264', '\u20d2'}, new[] {'\u003c', '\u20d2'},
                new[] {'\u22b4', '\u20d2'}, new[] {'\u2903'}, new[] {'\u22b5', '\u20d2'},
                new[] {'\u223c', '\u20d2'}, new[] {'\u21d6'}, new[] {'\u2923'}, new[] {'\u2196'},
                new[] {'\u2196'}, new[] {'\u2927'}, new[] {'\u24c8'}, new[] {'\u00f3'},
                new[] {'\u00f3'}, new[] {'\u229b'}, new[] {'\u229a'}, new[] {'\u00f4'},
                new[] {'\u00f4'}, new[] {'\u043e'}, new[] {'\u229d'}, new[] {'\u0151'},
                new[] {'\u2a38'}, new[] {'\u2299'}, new[] {'\u29bc'}, new[] {'\u0153'},
                new[] {'\u29bf'}, new[] {'\ud835', '\udd2c'}, new[] {'\u02db'}, new[] {'\u00f2'},
                new[] {'\u00f2'}, new[] {'\u29c1'}, new[] {'\u29b5'}, new[] {'\u03a9'},
                new[] {'\u222e'}, new[] {'\u21ba'}, new[] {'\u29be'}, new[] {'\u29bb'},
                new[] {'\u203e'}, new[] {'\u29c0'}, new[] {'\u014d'}, new[] {'\u03c9'},
                new[] {'\u03bf'}, new[] {'\u29b6'}, new[] {'\u2296'}, new[] {'\ud835', '\udd60'},
                new[] {'\u29b7'}, new[] {'\u29b9'}, new[] {'\u2295'}, new[] {'\u2228'},
                new[] {'\u21bb'}, new[] {'\u2a5d'}, new[] {'\u2134'}, new[] {'\u2134'},
                new[] {'\u00aa'}, new[] {'\u00aa'}, new[] {'\u00ba'}, new[] {'\u00ba'},
                new[] {'\u22b6'}, new[] {'\u2a56'}, new[] {'\u2a57'}, new[] {'\u2a5b'},
                new[] {'\u2134'}, new[] {'\u00f8'}, new[] {'\u00f8'}, new[] {'\u2298'},
                new[] {'\u00f5'}, new[] {'\u00f5'}, new[] {'\u2297'}, new[] {'\u2a36'},
                new[] {'\u00f6'}, new[] {'\u00f6'}, new[] {'\u233d'}, new[] {'\u2225'},
                new[] {'\u00b6'}, new[] {'\u00b6'}, new[] {'\u2225'}, new[] {'\u2af3'},
                new[] {'\u2afd'}, new[] {'\u2202'}, new[] {'\u043f'}, new[] {'\u0025'},
                new[] {'\u002e'}, new[] {'\u2030'}, new[] {'\u22a5'}, new[] {'\u2031'},
                new[] {'\ud835', '\udd2d'}, new[] {'\u03c6'}, new[] {'\u03d5'}, new[] {'\u2133'},
                new[] {'\u260e'}, new[] {'\u03c0'}, new[] {'\u22d4'}, new[] {'\u03d6'},
                new[] {'\u210f'}, new[] {'\u210e'}, new[] {'\u210f'}, new[] {'\u002b'},
                new[] {'\u2a23'}, new[] {'\u229e'}, new[] {'\u2a22'}, new[] {'\u2214'},
                new[] {'\u2a25'}, new[] {'\u2a72'}, new[] {'\u00b1'}, new[] {'\u00b1'},
                new[] {'\u2a26'}, new[] {'\u2a27'}, new[] {'\u00b1'}, new[] {'\u2a15'},
                new[] {'\ud835', '\udd61'}, new[] {'\u00a3'}, new[] {'\u00a3'}, new[] {'\u227a'},
                new[] {'\u2ab3'}, new[] {'\u2ab7'}, new[] {'\u227c'}, new[] {'\u2aaf'},
                new[] {'\u227a'}, new[] {'\u2ab7'}, new[] {'\u227c'}, new[] {'\u2aaf'},
                new[] {'\u2ab9'}, new[] {'\u2ab5'}, new[] {'\u22e8'}, new[] {'\u227e'},
                new[] {'\u2032'}, new[] {'\u2119'}, new[] {'\u2ab5'}, new[] {'\u2ab9'},
                new[] {'\u22e8'}, new[] {'\u220f'}, new[] {'\u232e'}, new[] {'\u2312'},
                new[] {'\u2313'}, new[] {'\u221d'}, new[] {'\u221d'}, new[] {'\u227e'},
                new[] {'\u22b0'}, new[] {'\ud835', '\udcc5'}, new[] {'\u03c8'}, new[] {'\u2008'},
                new[] {'\ud835', '\udd2e'}, new[] {'\u2a0c'}, new[] {'\ud835', '\udd62'},
                new[] {'\u2057'}, new[] {'\ud835', '\udcc6'}, new[] {'\u210d'}, new[] {'\u2a16'},
                new[] {'\u003f'}, new[] {'\u225f'}, new[] {'\u0022'}, new[] {'\u0022'},
                new[] {'\u21db'}, new[] {'\u21d2'}, new[] {'\u291c'}, new[] {'\u290f'},
                new[] {'\u2964'}, new[] {'\u223d', '\u0331'}, new[] {'\u0155'}, new[] {'\u221a'},
                new[] {'\u29b3'}, new[] {'\u27e9'}, new[] {'\u2992'}, new[] {'\u29a5'},
                new[] {'\u27e9'}, new[] {'\u00bb'}, new[] {'\u00bb'}, new[] {'\u2192'},
                new[] {'\u2975'}, new[] {'\u21e5'}, new[] {'\u2920'}, new[] {'\u2933'},
                new[] {'\u291e'}, new[] {'\u21aa'}, new[] {'\u21ac'}, new[] {'\u2945'},
                new[] {'\u2974'}, new[] {'\u21a3'}, new[] {'\u219d'}, new[] {'\u291a'},
                new[] {'\u2236'}, new[] {'\u211a'}, new[] {'\u290d'}, new[] {'\u2773'},
                new[] {'\u007d'}, new[] {'\u005d'}, new[] {'\u298c'}, new[] {'\u298e'},
                new[] {'\u2990'}, new[] {'\u0159'}, new[] {'\u0157'}, new[] {'\u2309'},
                new[] {'\u007d'}, new[] {'\u0440'}, new[] {'\u2937'}, new[] {'\u2969'},
                new[] {'\u201d'}, new[] {'\u201d'}, new[] {'\u21b3'}, new[] {'\u211c'},
                new[] {'\u211b'}, new[] {'\u211c'}, new[] {'\u211d'}, new[] {'\u25ad'},
                new[] {'\u00ae'}, new[] {'\u00ae'}, new[] {'\u297d'}, new[] {'\u230b'},
                new[] {'\ud835', '\udd2f'}, new[] {'\u21c1'}, new[] {'\u21c0'}, new[] {'\u296c'},
                new[] {'\u03c1'}, new[] {'\u03f1'}, new[] {'\u2192'}, new[] {'\u21a3'},
                new[] {'\u21c1'}, new[] {'\u21c0'}, new[] {'\u21c4'}, new[] {'\u21cc'},
                new[] {'\u21c9'}, new[] {'\u219d'}, new[] {'\u22cc'}, new[] {'\u02da'},
                new[] {'\u2253'}, new[] {'\u21c4'}, new[] {'\u21cc'}, new[] {'\u200f'},
                new[] {'\u23b1'}, new[] {'\u23b1'}, new[] {'\u2aee'}, new[] {'\u27ed'},
                new[] {'\u21fe'}, new[] {'\u27e7'}, new[] {'\u2986'}, new[] {'\ud835', '\udd63'},
                new[] {'\u2a2e'}, new[] {'\u2a35'}, new[] {'\u0029'}, new[] {'\u2994'},
                new[] {'\u2a12'}, new[] {'\u21c9'}, new[] {'\u203a'}, new[] {'\ud835', '\udcc7'},
                new[] {'\u21b1'}, new[] {'\u005d'}, new[] {'\u2019'}, new[] {'\u2019'},
                new[] {'\u22cc'}, new[] {'\u22ca'}, new[] {'\u25b9'}, new[] {'\u22b5'},
                new[] {'\u25b8'}, new[] {'\u29ce'}, new[] {'\u2968'}, new[] {'\u211e'},
                new[] {'\u015b'}, new[] {'\u201a'}, new[] {'\u227b'}, new[] {'\u2ab4'},
                new[] {'\u2ab8'}, new[] {'\u0161'}, new[] {'\u227d'}, new[] {'\u2ab0'},
                new[] {'\u015f'}, new[] {'\u015d'}, new[] {'\u2ab6'}, new[] {'\u2aba'},
                new[] {'\u22e9'}, new[] {'\u2a13'}, new[] {'\u227f'}, new[] {'\u0441'},
                new[] {'\u22c5'}, new[] {'\u22a1'}, new[] {'\u2a66'}, new[] {'\u21d8'},
                new[] {'\u2925'}, new[] {'\u2198'}, new[] {'\u2198'}, new[] {'\u00a7'},
                new[] {'\u00a7'}, new[] {'\u003b'}, new[] {'\u2929'}, new[] {'\u2216'},
                new[] {'\u2216'}, new[] {'\u2736'}, new[] {'\ud835', '\udd30'}, new[] {'\u2322'},
                new[] {'\u266f'}, new[] {'\u0449'}, new[] {'\u0448'}, new[] {'\u2223'},
                new[] {'\u2225'}, new[] {'\u00ad'}, new[] {'\u00ad'}, new[] {'\u03c3'},
                new[] {'\u03c2'}, new[] {'\u03c2'}, new[] {'\u223c'}, new[] {'\u2a6a'},
                new[] {'\u2243'}, new[] {'\u2243'}, new[] {'\u2a9e'}, new[] {'\u2aa0'},
                new[] {'\u2a9d'}, new[] {'\u2a9f'}, new[] {'\u2246'}, new[] {'\u2a24'},
                new[] {'\u2972'}, new[] {'\u2190'}, new[] {'\u2216'}, new[] {'\u2a33'},
                new[] {'\u29e4'}, new[] {'\u2223'}, new[] {'\u2323'}, new[] {'\u2aaa'},
                new[] {'\u2aac'}, new[] {'\u2aac', '\ufe00'}, new[] {'\u044c'}, new[] {'\u002f'},
                new[] {'\u29c4'}, new[] {'\u233f'}, new[] {'\ud835', '\udd64'}, new[] {'\u2660'},
                new[] {'\u2660'}, new[] {'\u2225'}, new[] {'\u2293'}, new[] {'\u2293', '\ufe00'},
                new[] {'\u2294'}, new[] {'\u2294', '\ufe00'}, new[] {'\u228f'}, new[] {'\u2291'},
                new[] {'\u228f'}, new[] {'\u2291'}, new[] {'\u2290'}, new[] {'\u2292'},
                new[] {'\u2290'}, new[] {'\u2292'}, new[] {'\u25a1'}, new[] {'\u25a1'},
                new[] {'\u25aa'}, new[] {'\u25aa'}, new[] {'\u2192'}, new[] {'\ud835', '\udcc8'},
                new[] {'\u2216'}, new[] {'\u2323'}, new[] {'\u22c6'}, new[] {'\u2606'},
                new[] {'\u2605'}, new[] {'\u03f5'}, new[] {'\u03d5'}, new[] {'\u00af'},
                new[] {'\u2282'}, new[] {'\u2ac5'}, new[] {'\u2abd'}, new[] {'\u2286'},
                new[] {'\u2ac3'}, new[] {'\u2ac1'}, new[] {'\u2acb'}, new[] {'\u228a'},
                new[] {'\u2abf'}, new[] {'\u2979'}, new[] {'\u2282'}, new[] {'\u2286'},
                new[] {'\u2ac5'}, new[] {'\u228a'}, new[] {'\u2acb'}, new[] {'\u2ac7'},
                new[] {'\u2ad5'}, new[] {'\u2ad3'}, new[] {'\u227b'}, new[] {'\u2ab8'},
                new[] {'\u227d'}, new[] {'\u2ab0'}, new[] {'\u2aba'}, new[] {'\u2ab6'},
                new[] {'\u22e9'}, new[] {'\u227f'}, new[] {'\u2211'}, new[] {'\u266a'},
                new[] {'\u00b9'}, new[] {'\u00b9'}, new[] {'\u00b2'}, new[] {'\u00b2'},
                new[] {'\u00b3'}, new[] {'\u00b3'}, new[] {'\u2283'}, new[] {'\u2ac6'},
                new[] {'\u2abe'}, new[] {'\u2ad8'}, new[] {'\u2287'}, new[] {'\u2ac4'},
                new[] {'\u27c9'}, new[] {'\u2ad7'}, new[] {'\u297b'}, new[] {'\u2ac2'},
                new[] {'\u2acc'}, new[] {'\u228b'}, new[] {'\u2ac0'}, new[] {'\u2283'},
                new[] {'\u2287'}, new[] {'\u2ac6'}, new[] {'\u228b'}, new[] {'\u2acc'},
                new[] {'\u2ac8'}, new[] {'\u2ad4'}, new[] {'\u2ad6'}, new[] {'\u21d9'},
                new[] {'\u2926'}, new[] {'\u2199'}, new[] {'\u2199'}, new[] {'\u292a'},
                new[] {'\u00df'}, new[] {'\u00df'}, new[] {'\u2316'}, new[] {'\u03c4'},
                new[] {'\u23b4'}, new[] {'\u0165'}, new[] {'\u0163'}, new[] {'\u0442'},
                new[] {'\u20db'}, new[] {'\u2315'}, new[] {'\ud835', '\udd31'}, new[] {'\u2234'},
                new[] {'\u2234'}, new[] {'\u03b8'}, new[] {'\u03d1'}, new[] {'\u03d1'},
                new[] {'\u2248'}, new[] {'\u223c'}, new[] {'\u2009'}, new[] {'\u2248'},
                new[] {'\u223c'}, new[] {'\u00fe'}, new[] {'\u00fe'}, new[] {'\u02dc'},
                new[] {'\u00d7'}, new[] {'\u00d7'}, new[] {'\u22a0'}, new[] {'\u2a31'},
                new[] {'\u2a30'}, new[] {'\u222d'}, new[] {'\u2928'}, new[] {'\u22a4'},
                new[] {'\u2336'}, new[] {'\u2af1'}, new[] {'\ud835', '\udd65'}, new[] {'\u2ada'},
                new[] {'\u2929'}, new[] {'\u2034'}, new[] {'\u2122'}, new[] {'\u25b5'},
                new[] {'\u25bf'}, new[] {'\u25c3'}, new[] {'\u22b4'}, new[] {'\u225c'},
                new[] {'\u25b9'}, new[] {'\u22b5'}, new[] {'\u25ec'}, new[] {'\u225c'},
                new[] {'\u2a3a'}, new[] {'\u2a39'}, new[] {'\u29cd'}, new[] {'\u2a3b'},
                new[] {'\u23e2'}, new[] {'\ud835', '\udcc9'}, new[] {'\u0446'}, new[] {'\u045b'},
                new[] {'\u0167'}, new[] {'\u226c'}, new[] {'\u219e'}, new[] {'\u21a0'},
                new[] {'\u21d1'}, new[] {'\u2963'}, new[] {'\u00fa'}, new[] {'\u00fa'},
                new[] {'\u2191'}, new[] {'\u045e'}, new[] {'\u016d'}, new[] {'\u00fb'},
                new[] {'\u00fb'}, new[] {'\u0443'}, new[] {'\u21c5'}, new[] {'\u0171'},
                new[] {'\u296e'}, new[] {'\u297e'}, new[] {'\ud835', '\udd32'}, new[] {'\u00f9'},
                new[] {'\u00f9'}, new[] {'\u21bf'}, new[] {'\u21be'}, new[] {'\u2580'},
                new[] {'\u231c'}, new[] {'\u231c'}, new[] {'\u230f'}, new[] {'\u25f8'},
                new[] {'\u016b'}, new[] {'\u00a8'}, new[] {'\u00a8'}, new[] {'\u0173'},
                new[] {'\ud835', '\udd66'}, new[] {'\u2191'}, new[] {'\u2195'}, new[] {'\u21bf'},
                new[] {'\u21be'}, new[] {'\u228e'}, new[] {'\u03c5'}, new[] {'\u03d2'},
                new[] {'\u03c5'}, new[] {'\u21c8'}, new[] {'\u231d'}, new[] {'\u231d'},
                new[] {'\u230e'}, new[] {'\u016f'}, new[] {'\u25f9'}, new[] {'\ud835', '\udcca'},
                new[] {'\u22f0'}, new[] {'\u0169'}, new[] {'\u25b5'}, new[] {'\u25b4'},
                new[] {'\u21c8'}, new[] {'\u00fc'}, new[] {'\u00fc'}, new[] {'\u29a7'},
                new[] {'\u21d5'}, new[] {'\u2ae8'}, new[] {'\u2ae9'}, new[] {'\u22a8'},
                new[] {'\u299c'}, new[] {'\u03f5'}, new[] {'\u03f0'}, new[] {'\u2205'},
                new[] {'\u03d5'}, new[] {'\u03d6'}, new[] {'\u221d'}, new[] {'\u2195'},
                new[] {'\u03f1'}, new[] {'\u03c2'}, new[] {'\u228a', '\ufe00'},
                new[] {'\u2acb', '\ufe00'}, new[] {'\u228b', '\ufe00'},
                new[] {'\u2acc', '\ufe00'}, new[] {'\u03d1'}, new[] {'\u22b2'}, new[] {'\u22b3'},
                new[] {'\u0432'}, new[] {'\u22a2'}, new[] {'\u2228'}, new[] {'\u22bb'},
                new[] {'\u225a'}, new[] {'\u22ee'}, new[] {'\u007c'}, new[] {'\u007c'},
                new[] {'\ud835', '\udd33'}, new[] {'\u22b2'}, new[] {'\u2282', '\u20d2'},
                new[] {'\u2283', '\u20d2'}, new[] {'\ud835', '\udd67'}, new[] {'\u221d'},
                new[] {'\u22b3'}, new[] {'\ud835', '\udccb'}, new[] {'\u2acb', '\ufe00'},
                new[] {'\u228a', '\ufe00'}, new[] {'\u2acc', '\ufe00'},
                new[] {'\u228b', '\ufe00'}, new[] {'\u299a'}, new[] {'\u0175'}, new[] {'\u2a5f'},
                new[] {'\u2227'}, new[] {'\u2259'}, new[] {'\u2118'}, new[] {'\ud835', '\udd34'},
                new[] {'\ud835', '\udd68'}, new[] {'\u2118'}, new[] {'\u2240'}, new[] {'\u2240'},
                new[] {'\ud835', '\udccc'}, new[] {'\u22c2'}, new[] {'\u25ef'}, new[] {'\u22c3'},
                new[] {'\u25bd'}, new[] {'\ud835', '\udd35'}, new[] {'\u27fa'}, new[] {'\u27f7'},
                new[] {'\u03be'}, new[] {'\u27f8'}, new[] {'\u27f5'}, new[] {'\u27fc'},
                new[] {'\u22fb'}, new[] {'\u2a00'}, new[] {'\ud835', '\udd69'}, new[] {'\u2a01'},
                new[] {'\u2a02'}, new[] {'\u27f9'}, new[] {'\u27f6'}, new[] {'\ud835', '\udccd'},
                new[] {'\u2a06'}, new[] {'\u2a04'}, new[] {'\u25b3'}, new[] {'\u22c1'},
                new[] {'\u22c0'}, new[] {'\u00fd'}, new[] {'\u00fd'}, new[] {'\u044f'},
                new[] {'\u0177'}, new[] {'\u044b'}, new[] {'\u00a5'}, new[] {'\u00a5'},
                new[] {'\ud835', '\udd36'}, new[] {'\u0457'}, new[] {'\ud835', '\udd6a'},
                new[] {'\ud835', '\udcce'}, new[] {'\u044e'}, new[] {'\u00ff'}, new[] {'\u00ff'},
                new[] {'\u017a'}, new[] {'\u017e'}, new[] {'\u0437'}, new[] {'\u017c'},
                new[] {'\u2128'}, new[] {'\u03b6'}, new[] {'\ud835', '\udd37'}, new[] {'\u0436'},
                new[] {'\u21dd'}, new[] {'\ud835', '\udd6b'}, new[] {'\ud835', '\udccf'},
                new[] {'\u200d'}, new[] {'\u200c'}
            };

        internal static readonly char[][] WINDOWS_1252 =
            {
                new[] {'\u20AC'}, new[] {'\u0081'},
                new[] {'\u201A'}, new[] {'\u0192'}, new[] {'\u201E'}, new[] {'\u2026'},
                new[] {'\u2020'}, new[] {'\u2021'}, new[] {'\u02C6'}, new[] {'\u2030'},
                new[] {'\u0160'}, new[] {'\u2039'}, new[] {'\u0152'}, new[] {'\u008D'},
                new[] {'\u017D'}, new[] {'\u008F'}, new[] {'\u0090'}, new[] {'\u2018'},
                new[] {'\u2019'}, new[] {'\u201C'}, new[] {'\u201D'}, new[] {'\u2022'},
                new[] {'\u2013'}, new[] {'\u2014'}, new[] {'\u02DC'}, new[] {'\u2122'},
                new[] {'\u0161'}, new[] {'\u203A'}, new[] {'\u0153'}, new[] {'\u009D'},
                new[] {'\u017E'}, new[] {'\u0178'}
            };
    }
}